### ISSUE TITLE
Silently fails/stalls webpack with no error

### ISSUE THREAD

**Issue by evandegr** [jtangelder/sass-loader#100]
I have 2 imports that I use in multiple scss files that look like the following:

```
@import 'variables';
@import 'functions';
```

Everything works fine until I hit one file that has the exact same imports. Then, I see webpack build stall and it shows no errors. If I remove the import for this file, everything works, if I add it, it stalls. I don't understand why its happening because it's using the exact same imports. Problem still occurs if I remove everything in that file except for the imports. Problem does not occur if I remove the imports as well.

**Comment by maman** [comment]
got this issue too.

the directory structure is something like this. 

```
├── moduleA
│   ├── moduleA.controller.js
│   ├── moduleA.style.scss
│   ├── moduleA.template.html
├── moduleB
│   ├── moduleB.controller.js
│   └── moduleB.style.scss
│   ├── moduleB.template.html
├── moduleC
│   ├── moduleC.controller.js
│   ├── moduleC.style.scss
│   └── moduleC.template.html
├── styles
│   ├── _settings.scss
│   └── main.scss
└── app.js
```

1. the module-specific styles will be `require`’d in the `controller`. 
2. all module-specific styles has `@import` syntax to `_settings.scss` file.
3. the main.scss is the ‘global’ stylesheet which `require`’d in the `app.js` file, and has `@import` syntax to `_settings.scss` file.

also I used `foundation-apps` library heavily, so `main.scss` file has `@import` to the `foundation-apps/foundation`, and the module-specific styles has `@import` to some foundation functions that I use for the module, such as `foundation-apps/components/grid`.

the build succeeds when I first remove the `require` on the `controller`, and add it again after the first build has succeed (I use webpack-dev-server with --hot).

**Comment by jhnns** [comment]
That's strange, thx for reporting this. Could you set up a small gist that reproduces the error?

**Comment by saper** [comment]
Does putting `env UV_THREADPOOL_SIZE=100` before `node` invocation help? If yes, then this is sass/node-sass#857

**Comment by Antontelesh** [comment]
I'm reporting the same issue.
Putting `env UV_THREADPOOL_SIZE=100` before `webpack` invocation does not help.

**Comment by Antontelesh** [comment]
Sorry, it helps but builds very slowly. I've been waiting for a couple of minutes and it have compiled after all :)

**Comment by maman** [comment]
@jhnns sorry I can't, still in the middle of a project :persevere:
currently I'm using the `env UX_THREADPOOL_SIZE=100`, and it definitely helps. thanks @saper !
still curious about what the line doing though, care to explain?

**Comment by evandegr** [comment]
Also downgrading to 0.5.0 and using node-sass 3.1.1 fixed this for me.

**Comment by saper** [comment]
3.1.1 also suffers from threading problem, so there must be some other, additional issue. @evandegr can you post somewhere a minimal but complete example to reproduce this issue?

**Comment by ftorre104** [comment]
I had this same issue. It happens when I import a utility .scss file (it has mixins) into 2 or more other scss files. If I just import it into 1 scss file, webpack builds correctly.

However, I have no problem with config .scss files that only define variables. I can include those into as many .scss files with no build problem.

`env UX_THREADPOOL_SIZE=100` worked for me too.

**Comment by jeffling** [comment]
Weird, I have the same problem and fixed it by downgrading to 0.5.0.

**Comment by haustraliaer** [comment]
We experienced this issue as well - multiple imports of a global (`@import '~boilerplate';`) mixin/variable file completely stalled webpack.

**Comment by saper** [comment]
I would really love if webpack community could produce a simple, self-contained setup to reproduce the issue.

**Comment by haustraliaer** [comment]
@saper I'm literally doing that right now ;)

**Comment by jeffling** [comment]
@haustraliaer nice! :) i was going going to do it this weekend but ran out of time. Would really love to get this resolved so we can stop adding 30 sass include paths into our build. Let me know if you need any help!

**Comment by piotrf** [comment]
I have a sample for you to fiddle with: https://github.com/piotrf/webpack-playground

1. `npm install` and `npm start` 
2. terminal will throw SASS variables missing errors.
3. uncomment `@import "config";` in those files:

```
/src/Modules/Footer/Footer.scss
/src/Modules/Header/Header.scss
/src/Modules/StatusBar/StatusBar.scss
```

4. bundle will recompile.
5. restart server.
6. bundle compilation will choke.

Hope that helps.

**Comment by haustraliaer** [comment]
Hah, beat me to it... Here's my project anyway which shows pretty clearly where it breaks:

https://github.com/haustraliaer/sass-webpack

**Comment by mmahalwy** [comment]
Any updates on this? Still not working and hangs :(

**Comment by haustraliaer** [comment]
@mmahalwy It seems like the node-sass guys are gonna take a while to update this issue - as it's not a simple problem to fix.

I'm honestly about to bail on sass in favour of postcss.

**Comment by saper** [comment]
Dzięki, @piotrf 

Right now I am getting the same `Module not found: Error: Cannot resolve 'file' or 'directory' ./modules/TopBar/TopBar` error for 4 modules, no matter what :)

With https://github.com/saper/webpack-playground/tree/uncommenting@f547bb0 I get:

https://gist.github.com/e0ec0e85bc048922ca27

With the master (https://github.com/saper/webpack-playground/commit/f547bb09dc7cd70ccc6b752fad13942fa506ba64) is gives

https://gist.github.com/9255315d068b8edc36b

Not a big difference, if any....

**Comment by mmahalwy** [comment]
@haustraliaer great suggestion! PostCss looks amazing!

**Comment by jhnns** [comment]
@haustraliaer 's example shows the hangs.

**Comment by dexbol** [comment]
`process.env.UV_THREADPOOL_SIZE = 100;` works .

**Comment by saper** [comment]
I can unfortunately confirm that https://github.com/haustraliaer/sass-webpack hangs due to sass/node-sass#857

**Comment by ebordeau** [comment]
`UV_THREADPOOL_SIZE=100` also worked for me.

**Comment by dmitry** [comment]
I've checked versions `>= 0.5.0`. Only 0.5.0 is working, everything after `0.6.0` stalls somewhere in the middle of a build.

**Comment by karlnp** [comment]
thanks, @dmitry - this lets me keep working. Appreciated.

**Comment by dmitry** [comment]
@karlnp hopefully someone who is more experienced with `sass-loader` will fix this issue soon and we (who stuck with this issue) will be able to use newer versions of it.

**Comment by MozMorris** [comment]
@dmitry thanks, this helped me.

**Comment by loopmode** [comment]
@dmitry thanks, works for me too.
Unfortunately, the release log jumps from v0.3.1 to v1.0.0, so it is not clear what features or changes we miss when using 0.5.0, but everything seems to work fine so far (using bourbon/neat/bitters)

**Comment by karlnp** [comment]
@loopmode I thought you were commenting on what you were drinking - and googling it led to the discovery that neat/bitters neatly solves a problem we've been wrestling with. thank you!

**Comment by loopmode** [comment]
@karlnp xD it's easy to forget you're using specific slang when you're deep in some development and libraries

**Comment by jcreamer898** [comment]
Had the same issue and the `UV_THREADPOOL_SIZE=100` variable solved it for now.

**Comment by patrickhaug** [comment]
how can i use this renderSync?

**Comment by patrickhaug** [comment]
is there an update on this? webpack get's really slow with renderSync.

**Comment by laurentvd** [comment]
I'm having similar issues and UV_THREADPOOL_SIZE solves it (for now)

**Comment by dmitry** [comment]
Does anyone understands what causes this issue, so it can be fixed?

**Comment by jorrit** [comment]
It is explained by saper in sass/node-sass#857. The 4 internal threads are occupied by node-sass and then sass-loader tries to import a file from the filesystem, which stalls until one of the threads becomes available. This never happens.

**Comment by laurentvd** [comment]
Ah great to have an understandable explanation! Thanks @jorrit and @saper

**Comment by jcreamer898** [comment]
When someone says it's a threading issue...

![](http://i41.tinypic.com/25rig5e.gif)

**Comment by dmitry** [comment]
@jorrit :+1:

Basically it's not related to the sass-loader, but completely related to node-sass?

**Comment by jorrit** [comment]
Mostly, yes. But maybe node-sass can work around it, but I am not certain.

**Comment by jhnns** [comment]
I would be happy to provide a temporary fix, but #109 seems a bit risky to me...

**Comment by jorrit** [comment]
Please see #132 for a possible fix.

**Comment by pthorn** [comment]
I also have this problem. UV_THREADPOOL_SIZE=100 seems to help.

**Comment by jorrit** [comment]
Did you take a look at #132 ?

**Comment by pthorn** [comment]
#132 seems to fix #100. Thanks for the hint.

**Comment by jorrit** [comment]
And thanks to you for testing!

**Comment by danielstefanovic** [comment]
#132 works for me too.

**Comment by jedwards1211** [comment]
So there's no single-threaded or pure JS Sass compiler, is there?  I would be all in favor of switching to one if it exists

**Comment by alexilyaev** [comment]
I'm still having this issue.

I"ve updated to `sass-loader` `2.0.1` and it installed `node-sass` `3.3.3` and my WebPack build still hangs at `build modules` (around 68%)

Adding `UV_THREADPOOL_SIZE=100` before the command did not help.
I even deleted the whole `node_modules` folder and installed again, still hangs.

Removing the loader from the Webpack config results in a successful build (albeit with errors related to my scss files).

How come it fails silently?
Can't we have some errors shown?

**Comment by alexilyaev** [comment]
After more digging, turns out I had a different issue altogether, created a new ticket for that #168.
After dealing with that, the build passed correctly with the `sass-loader` `2.0.1`.

**Comment by mderrick** [comment]
Just in case this helps anybody I also had this precise issue with importing a partial just fine until I imported it again for the third time. Webpack would simply hang.

Upgrading `sass-loader` from `1.0.1` to `3.1.2` solved it for me.

**Comment by pavankumarkatakam** [comment]
yeah, upgrading the sass-loader version solved for me also, thanks @mderrick

**Comment by sebastiaanluca** [comment]
Running into the same issue using a simple mixin, but not sure of it's entirely the same or whether I should create a new issue. Using `"sass-loader": "^3.1.2"`

```sass
@mixin font-sans($font: 'Lato') {
    font-family: $font, sans-serif;
    font-style: normal;
}

@mixin font-sans-light {
    @include font-sans();
    font-weight: 300;
}
```

Note the `@include font-sans()` and its parenthesis. Passing something like `@include font-sans('Lato');` works. Not passing something just silently stops gulp/webpack watch after just showing `Begin compile at…` and `Finished 'webpack'…`.

**Comment by bensampaio** [comment]
I just run into this exact same issue. I'm using `"css-loader": "^0.23.1"` in combination with `"sass-loader": "^4.0.0"`. Every CSS module file imports the same `vars.scss` file. At first, that was fine but the project continued growing so I got more and more .scss files and now all of a sudden `webpack` is no longer able to finish.

My webpack configuration looks like this:

```js
{
    devtool: 'eval',
    entry: {
    	app: path.resolve(__dirname, 'start.js'),
    },
    module: {
        loaders: [
            {
                loader: 'babel',
                test: /\.jsx?$/,
            },
            {
                loader: ExtractTextPlugin.extract('css?modules&importLoaders=1&localIdentName=[name]--[local]___[hash:base64:5]!sass!postcss-loader'),
                test: /\.scss$/,
            },
        ],
    },
    plugins: [
        new ExtractTextPlugin('styles.css', { allChunks: true }),
    ],
    postcss: [
        Autoprefixer,
    ],
    output: {
    	path: path.resolve(__dirname, 'dist'),
    	filename: '[name].js',
    },
    resolve: {
        extensions: ['', '.js', '.jsx'],
    },
    watch: true,
}
```

Am I doing anything wrong? Is this a known problem of using CSS modules with SASS? Is there anything I can try to fix this either temporarily or permanently? Help with this would be truly appreciated since I'm completely stuck with this issue. Thank you!

**Comment by feychou** [comment]
This still happens to me with `node-sass 3.8.0` and `sass-loader 4.0.0`. However increasing the threadpoll size works.

**Comment by theskillwithin** [comment]
happens     "sass-loader": "^4.0.2",

**Comment by tomsarduy** [comment]
This is still happening, 2 years and there is no final resolution? I'm using `node-sass 4.5.0` and `sass-loader 6.0.1`. Although `UV_THREADPOOL_SIZE=100` seems to solve the issue, it makes the compilation time slower. I'm afraid what's gonna happen when the project keeps growing.

**Comment by jhnns** [comment]
If someone can publish a project that makes this reproducible, that would be a big help 👍

**Comment by jsg2021** [comment]
From what i can gather, it's really a cyclical import issue. I don't think there's anything to do for sass-loader other than to detect/report the problem for the user to fix.

**Comment by feychou** [comment]
@jhnns had this problem with https://github.com/kununu/nukleus ^^

**Comment by mechanicious** [comment]
Webpack stalled at compiling Javascript files through babel. 

Adding the option below to `webpack.config.js` solved the issue for me. This option is described in [docs](https://webpack.js.org/configuration/watch/#watchoptions-poll).
```js
watchOption: {
  poll: 1000
}
```
