### ISSUE TITLE
Cannot import CSS files

### ISSUE THREAD

**Issue by jhnns** [jtangelder/sass-loader#101]
https://github.com/jtangelder/sass-loader/issues/91#issuecomment-103121653

**Comment by adamalbrecht** [comment]
+1

**Comment by elektronik2k5** [comment]
+1

**Comment by cmnstmntmn** [comment]
+1

**Comment by newtriks** [comment]
+1

**Comment by Undistraction** [comment]
+1

**Comment by malte-wessel** [comment]
+1

**Comment by laskos** [comment]
+1!

**Comment by jorrit** [comment]
Can you try the changes in PR #116 to see if it is fixed?

**Comment by zallek** [comment]
:+1:

**Comment by kisenka** [comment]
+1

**Comment by jsg2021** [comment]
Hello again :)

in the example in #91 about my fonts.scss file... the compiled output does not include the contents of the `.css` files instead has a file-system absolute path in an `@import url(...);` statement. 

See: (newlines added for readability) 
```css
@import url(/Users/jgrimes/Workspace/nti.web.mobile/src/main/resources/fonts/droid-serif/index.css);
@import url(/Users/jgrimes/Workspace/nti.web.mobile/src/main/resources/fonts/foundation-icons/index.css);
@import url(/Users/jgrimes/Workspace/nti.web.mobile/src/main/resources/fonts/open-sans/index.css);
@import url(/Users/jgrimes/Workspace/nti.web.mobile/src/main/resources/fonts/open-sans-condensed/index.css);
@import url(/Users/jgrimes/Workspace/nti.web.mobile/src/main/resources/fonts/stix/index.css);
@import url(/Users/jgrimes/Workspace/nti.web.mobile/src/main/resources/fonts/symbola/index.css);
@import url(/Users/jgrimes/Workspace/nti.web.mobile/src/main/resources/fonts/icomoon/style.css); 
...
```

Those file paths are correct (from the file system's perspective)... I would expect the contents of the css file to be inlined. (as sass-loader did in 0.4.x)

**Comment by jsg2021** [comment]
I think I understand some of this more...

Sass will compile `@import "plain.css"` into `@import url(plain.css);` and not inline it.

WebPack may not be given the opportunity to re-resolve the css file and pack it in.

**Comment by jsg2021** [comment]
@jhnns @jorrit any thoughts?

**Comment by jhnns** [comment]
Could you guys check out the current master branch and check if it works for you? I've heavily refactored the import mechanism and need more tests.

**Comment by jsg2021** [comment]
So, CSS files are being imported. yay!

However, the references in them to fonts and images are not respecting the CSS path. (relative urls in plain css are relative to the css file's path)

**Comment by jsg2021** [comment]
Disregard. :) leaving the `.css` extension on the import statement makes it work as expected! :)

**Comment by jorrit** [comment]
Does anyone know why there is a difference?

**Comment by jsg2021** [comment]
@jorrit If my understanding is correct, not including an extension the loader looks for .sass, .scss and .css...but treats them as if they were sass.  With an extension, it seem to be passing it to webpack (as it should be)

Perhaps, the css ***without*** extension should log a warning letting the author know that this style of import is quirky.

**Comment by jhnns** [comment]
@jsg2021 When you add the `.css` extension, libsass does not include the file, it just turns it into `@import url(..)`. When this is passed to the css-loader, all urls must be relative to the file which imports them. When you omit `.css`, libsass includes the file just like it was a `.scss` file. In this situation, all urls must be relative to the entry sass/scss file which was passed to the sass compiler.

This is how libsass handles it, [the sass-loader is just imitating it](https://github.com/jtangelder/sass-loader/blob/089c52dc9bd02ec67fb5c65c2c226f43710f231c/index.js#L293-L348).

**Comment by jsg2021** [comment]
@jhnns I think thats perfect.

**Comment by jschlieber** [comment]
> When you add the .css extension, libsass does not include the file, it just turns it into @import url(..). When this is passed to the css-loader, all urls must be relative to the file which imports them. When you omit .css, libsass includes the file just like it was a .scss file. In this situation, all urls must be relative to the entry sass/scss file which was passed to the sass compiler.

@jhnns Is this still the expected behavoir? Because if I omit `.css` in my import statement the file is completely ignored. It works if I add `.css` but then I have the problem with the relative urls. I'm on `sass-loader` version `6.0.3`...

**Comment by esr360** [comment]
I am importing a sibling CSS file into my main CSS file. Compile fine usually, but using sass-loader I get this error:

```
ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"outputStyle":"expanded"}!./src/app.scss
Module not found: Error: Can't resolve './flickity.css' in '/Users/edmund/Projects/One-Nexus-Homepage/One-Nexus/src'
 @ ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"outputStyle":"expanded"}!./src/app.scss 3:10-73
 @ ./src/app.scss
```

My `.scss` file contains `@import 'flickity.css';`, as it is a sibling stylesheet it exists in the same output directory, and I can see the file exists on the webpack-server. Is there anyway to get this to work without having to modify my `.scss` files?

**Comment by esr360** [comment]
I have a setup like this in my main `.scss` file:

```
// Sass librarys
@import '../../node_modules/spinners/stylesheets/spinners';

// CSS librarys
@import 'flickity.css'
```

Naturally the Sass libraries are relative to the Sass file they are imported into, but the CSS libraries are relative to the output CSS file.

Trying to compile the above with Webpack sass-loader results in the following error:

```
ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"importer":[null],"outputStyle":"expanded"}!./src/app.scss
Module not found: Error: Can't resolve './flickity.css' in '/Users/edmund/Projects/One-Nexus-Homepage/One-Nexus/src'
 @ ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"importer":[null],"outputStyle":"expanded"}!./src/app.scss 3:10-73
```

However, if I change the above to:

```
// Sass librarys
@import '../../node_modules/spinners/stylesheets/spinners';

// CSS librarys
@import '../../node_modules/flickity/dist/flickity.css';
```

It appears to work properly. I would like my app to not depend upon Webpack and compile with regular Sass - is there anyway to do this without modifying my `.scss` file?

**Comment by bs-thomas** [comment]
I have the same issue.  Wonder if this is being looked at.
