### ISSUE TITLE
Is it possible to namespace to the classes?

### ISSUE THREAD

**Issue by brandondurham** [jtangelder/sass-loader#103]
I'd love to be able to namespace my classes being imported by sass-loader. Is this possible?

**Comment by jeffling** [comment]
I had this problem too, and I ended up having to do this: https://github.com/jeffling/namespace-css-loader 

css-loader also has a way to do it that wasn't compatible with our project.

**Comment by jhnns** [comment]
Interesting @jeffling :+1: 

I think it's also possible to just do something like

```javascript
#my-namespace {
    @import "all/that/stuff";
}
```

**Comment by jeffling** [comment]
^ That's probably the way if you load your sass from the top down :)

**Comment by jhnns** [comment]
Yep. To be honest, I haven't found a way the other way round without code duplication.
