### ISSUE TITLE
webpack freezes when require more than three scss files.

### ISSUE THREAD

**Issue by dexbol** [jtangelder/sass-loader#106]
Example.

There are 5 scss files: a, b, c, d, v, and 1 entry file entry.js

v.scss: `$color:red;`
a.scss: `@import 'v'; .a{color:$color}`
b.scss: `@import 'v'; .b{color:$color}`
c.scss: `@import 'v'; .c{color:$color}`
d.scss: `@import 'v'; .d{color:$color}`

entry.js:
`require('a.scss');require('b.scss');require('c.scss');require('d.scss');`

webpack loader config:

`{test: /\.scss$/, loader: 'style!css!sass'}`

If replace `@import 'v'` by `$color:red` in a/b/c/d files, the webpack is fine. If I remain 3 or less 3 files, it is fine too.

**Comment by jhnns** [comment]
That's a confirmed concurrency issue of node-sass 3. See #100
