### ISSUE TITLE
WebpackDevServer doesn't work with ExtractTextPlugin and sass-loader

### ISSUE THREAD

**Issue by fongandrew** [jtangelder/sass-loader#125]
More details here: https://github.com/webpack/extract-text-webpack-plugin/issues/88

Basically, I'm using a basic SASS loader setup with the ExtractTextPlugin and the dev server watching:

```
module: {
  loaders: [
    {  test: /\.scss$/,
       loader: ExtractTextPlugin.extract("style-loader", "css!sass") }
},

plugins: [
  new ExtractTextPlugin("bundle.css", {allChunks: true})
]
```

When the dev server reloads, I get a `The callback was already called` error. It seems similar to this error with the LESS loader (https://github.com/webpack/less-loader/issues/18). Any chance the SASS loader could have a similar bug?

**Comment by jorrit** [comment]
Can you create a repository with a complete test situation?

**Comment by fongandrew** [comment]
Repro is here: https://github.com/fongandrew/webpack-extract-sass-test/tree/master

Weirdly, it only occurs when awesome-typescript-loader is used. It might be their issue.

**Comment by jorrit** [comment]
This was fixed in s-panferov/awesome-typescript-loader

**Comment by fongandrew** [comment]
Yup, fix works. Closing this issue.
