### ISSUE TITLE
Issue with path resolving on Windows

### ISSUE THREAD

**Issue by ALF-er** [jtangelder/sass-loader#127]
Hi guys. Have issue on Windows 10 with sass-loader@1.0.3. Simple example: https://github.com/ALF-er/wp_test simple import of bootstrap.css from node_modules. But receive error:
```
ERROR in ./~/css-loader!./~/sass-loader?includePaths[]=C:/dev/projects/wp_test/node_modules!./src/app/entrypoints/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ./C:\dev\projects\wp_test\node_modules\bootstrap\dist\css\bootstrap.css in C:\dev\projects\wp_test\src\app\entrypoints
 @ ./~/css-loader!./~/sass-loader?includePaths[]=C:/dev/projects/wp_test/node_modules!./src/app/entrypoints/main.scss 2:10-146
```

just run 
```
npm install 
npm run dev
```

Where I'm wrong? =|

**Comment by jorrit** [comment]
I have tried to find out what is wrong here, but I can't find it. Somewhere webpack prepends `./` to the file name.

**Comment by jhnns** [comment]
I've checked it on my virtual machine. Your example passes the sass-loader without error, but the css file is imported with an absolute path. This behavior is not intended (see #138).

However, it should be no problem for the css-loader, but it seems like the css-loader [is not able to recognize absolute Windows paths](https://github.com/webpack/loader-utils/blob/a8610120db7bcdde249cbf7bcaa5f8ce65aa318d/index.js#L118) @sokra.

**Comment by jhnns** [comment]
Could you guys check out the current master branch and check if it works for you? I've heavily refactored the import mechanism and need more tests.

**Comment by ALF-er** [comment]
```
ERROR in ./~/css-loader!./~/sass-loader?includePaths[]=C:/dev/projects/wp_test/node_modules!./src/app/entrypoints/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ./C:Þvprojectswp_testnode_modulesbootstrapdistcssbootstrap.css in C:\dev\projects\wp_test\src\app\entrypoints
 @ ./~/css-loader!./~/sass-loader?includePaths[]=C:/dev/projects/wp_test/node_modules!./src/app/entrypoints/main.scss 3:10-129
```
for me =(

**Comment by jhnns** [comment]
Thx for the feedback. I've found the problem and I'm working on it...
