### ISSUE TITLE
Is there any elegant way to load bootstrap-sass and make a few customizations?

### ISSUE THREAD

**Issue by greaber** [jtangelder/sass-loader#133]
With straightforward loader configuration, I can load bootstrap from the bootstrap-sass module like so:

``` javascript
require('bootstrap-sass/assets/stylesheets/_bootstrap.scss')
require('bootstrap-sass/assets/javascripts/bootstrap.js')
```

However, I would like to customize bootstrap by omitting some files and changing some variables.  I found a module specifically for this exact task called bootstrap-sass-loader, but it seems absurd that a special module would be needed, and I would rather not have that sort of incidental complexity in my project.  Some other things I considered are:
- Maybe there is either a general node module or something webpack-specific that lets you use patched versions of modules or other resources, and I could express my customizations as a patch against bootstrap-sass?
- I could copy _bootstrap.scss, _variables.scss, and _mixins.scss into my project and tweak them.  But that that will require either very extensive changes to those files or some clever webpack config I have not yet been able to find.  I thought that it should be enough to change _bootstrap.scss to import my versions of _variables.scss and _mixins.scss and then to add some "includePaths[]" options, but I could only get scss files to work that way, not fonts.  Another possibility might be to mess with webpack's resolution system, since @import apparently goes through the webpack resolution system.  But it looks like that might require writing a plugin?

I must be making things harder than they really are...

**Comment by jorrit** [comment]
Have you looked at https://github.com/justin808/bootstrap-sass-loader ?

**Comment by greaber** [comment]
Yeah, I was kind of shocked that it should be that complicated, but maybe I just need to get over that :)

**Comment by tappleby** [comment]
I use the following setup:

app.scss:
```scss
@import "config/bootstrap";
@import "~bootstrap-sass/assets/stylesheets/bootstrap";
```

config/_bootstrap.scss:
```scss
$icon-font-path: '~bootstrap-sass/assets/fonts/bootstrap/';
// ... other custom variables
```

The issue I am running into with this setup is sass build times spike to ~2.3 seconds... havent been able to figure out why.

**Comment by smashercosmo** [comment]
@tappleby could you explain, how did you make it work? I get this error
```
ERROR in ./src/index.js
Module not found: Error: Cannot resolve module '~bootstrap-sass/assets/stylesheets/bootstrap' in /Users/smashercosmo/Documents/Projects/bootstrap/src
 @ ./src/index.js 2:0-55
```
my webpack config
```javascript
module.exports = {
  entry: {
    app: './src/index.js'
  },
  output: {
    path: './dist',
    filename: '[name].js'
  },
  module: {
    loaders: [{
      test: /\.scss$/,
      loader: 'style!css!sass'
    }]
  }
};
```
my index.js
```javascript
require('./app.scss');
require('~bootstrap-sass/assets/stylesheets/bootstrap');
```

**Comment by jhnns** [comment]
This is not an issue specific to the sass-loader so I'll close it. @tappleby thanks for providing an example setup.
