### ISSUE TITLE
Compilation never finishes when there is an @import in the file

### ISSUE THREAD

**Issue by volkanunsal** [jtangelder/sass-loader#136]
I'm using the latest version, 1.0.3. I noticed the imports have been broken for the past few releases; the latest solution doesn't seem to work.

**Comment by volkanunsal** [comment]
Here is an example of an import:

```scss
@import "components/mixins";
```

**Comment by volkanunsal** [comment]
Adding `UV_THREADPOOL_SIZE=100` solved it for me.

**Comment by jorrit** [comment]
Just out of curiosity: does the change in PR #132 solve the issue too?

**Comment by volkanunsal** [comment]
I haven't tried that. This one seems to work, but I'd prefer if the package had that solution already.

**Comment by jorrit** [comment]
I am not sure yet if that is a solution. I can help you try #132 if you want. You can always revert to the original package afterwards. If you change `"sass-loader": "1.0.3"` to `"sass-loader": "jorrit/sass-loader#async"` in your `package.json` and do `npm update`, you should get the other version. You can change it back to get the regular version.
