### ISSUE TITLE
indented syntax not working

### ISSUE THREAD

**Issue by lili21** [jtangelder/sass-loader#139]
node-sass: 3.2.0
sass-loader: 2.0.0
```
{test: /\.sass$/, loader: 'style-loader!css-loader!sass-loader?indentedSyntax=true'}
```

error message
```
Invalid top-level expression
```

**Comment by jhnns** [comment]
There are tests for the indented syntax, so I expect it to work. Please provide a minimal example that demonstrates the problem.

**Comment by lili21** [comment]
It works now. You can close the issue now.

**Comment by Lordnibbler** [comment]
@lili21 i got this same error, any explanation of how you resolved it/

**Comment by lili21** [comment]
@Lordnibbler Actually, I just closed laptop, went home, and sleep. Then next day, It just works, like a magic.
