### ISSUE TITLE
Firefox doesn't like source-map comment syntax

### ISSUE THREAD

**Issue by rtlong** [jtangelder/sass-loader#143]
In Firefox (I'm using 39.0.3), the source-map comment in the compiled CSS doesn't work. I've determined it's due to a missing space between the end of the URL and the `*/`. Chrome doesn't seem to mind this, and I'm not sure if it meets the spec this way or not. I've also determined that node-sass doesn't exhibit this behavior when invoked directly. I could provide a minimal repro if need be; just let me know.

**Comment by rtlong** [comment]
Also, checked that using `node-sass@3.2.0` and `sass-loader@2.0.0`

**Comment by rtlong** [comment]
Huh... wouldn't you know it. I upgrade to Firefox 40.0 and now it's less picky. Well, nevermind, then...

**Comment by jhnns** [comment]
Nice :grinning:
