### ISSUE TITLE
'problems with url()' no longer a problem?

### ISSUE THREAD

**Issue by bholloway** [jtangelder/sass-loader#144]
Awesome loader.

In your `readme.md` you note the [problem](https://github.com/jtangelder/sass-loader#problems-with-url) we have all encountered with relative `url()` statements in SASS.

I have written a [resolve-url-loader](https://www.npmjs.com/package/resolve-url-loader) which I hope addresses the issue and I would value your opinion.

It is actually a port of some code I have been using in **Browserify** for quite a while on a number of large projects. I am less familiar with **Webpack** and defer to your greater experience.

**Comment by jhnns** [comment]
I did just skim through your source code and it looks good! :+1: You did even use `urlToRequest()`. Would you mind sending me a PR with the updated README? I would be happy to mention your loader.

I was just wondering if this behavior could/should be part of the css-loader when source maps are present. In this case we could avoid parsing the CSS twice.

**Comment by bholloway** [comment]
Will get going on a PR.

I think you are correct in your existing `readme.md` where you imply that the root of the problem is with Sass.

\<rant\>
I believe the traditional use is a root `scss` file and a set of library files prefixed with an underscore. The assets being specified relative to the output `css`, not any of the `scss` source files. This makes all *fully relative* references *root-relative* to the output folder. This is counter-intuitive and completely at odds with `css` files where a *fully relative* `url()` is relative to the `css` in which it is specified.

In particular it makes it difficult to cherry-pick files from different libraries. We must resolve all references through the library root, which may not be reliably detectable. Frameworks such as **bootstrap-sass** are forced to compose `url()` with variables to allow users to work around their individual use case.
\</rant\>

Given that we are correcting this behaviour, it would be more correct to encapsulate this in the **sass** loader rather than address it in the **css** loader, regardless of where the efficiencies lie.

That said the [convention](http://webpack.github.io/docs/how-to-write-a-loader.html#do-only-a-single-task) is against being monolithic. And for those comfortable with the standard sass behaviour you could certainly save them the parsing and synchronous file-system operations.

I would suggest you judge the reaction to this solution. If it proves to be successful, and your dominant use case, you should consider encapsulating the functionality into the **sass-loader**.

**Comment by Shinobi881** [comment]
@bholloway You rock so freaking hard!!!!
