### ISSUE TITLE
In 2.0.0+ importing using `~module` is unable to resolve

### ISSUE THREAD

**Issue by lencioni** [jtangelder/sass-loader#149]
Before upgrading to 2.0.0+, I was using some imports like the following:

```scss
@import '~config';
```

[According to the documentation](https://github.com/jtangelder/sass-loader#imports), this should tell sass-loader to have webpack resolve these paths using `modulesDirectories`:

> Just prepend them with a ~ which tells webpack to look-up the modulesDirectories.

This was working great for me, but when I upgrade to 2.0.0 or 2.0.1, I get the following error when webpack runs:

```
Module build failed:
@import '~config';
       ^
      File to import not found or unreadable: ~config
```

Is there a new way I should be doing this, or is this feature no longer supported as of 2.0.0?

Thanks!

**Comment by jerrysu** [comment]
Same here. I am trying to upgrade from 0.4.2.

**Comment by grrowl** [comment]
Same here (upgrading from 0.4.x), in my case I'm adding `require('node-bourbon').includePaths` to the includePaths[]`, but `@import "~bourbon";` yields this error:
```
@import "~bourbon";
       ^
      File to import not found or unreadable: ~bourbon/Users/tom/Documents/project/src/css/
```


Using `@import "~node-bourbon/assets/stylesheets/bourbon";` works though, so it's either not looking at `includePaths` any more in favour of the webpack loader, or won't resolve underscored scss files at module root.

**Comment by tomatau** [comment]
Same here

**Comment by adriaanbalt** [comment]
Same

**Comment by mako-taco** [comment]
This actually works for me on OSX, but fails on linux.

**Comment by jhnns** [comment]
@lencioni your assumptions are right. Everything starting with `~` should be read from your `modulesDirectories`, usually `node_modules`.

However, if you just write

```javascript
@import '~config';
```

webpack will read `config`'s `package.json` to get the main entry point which is usually a JS-file. Have you tried importing specific stuff by writing

```javascript
@import '~config/variables.scss';
```

?

[There are tests](https://github.com/jtangelder/sass-loader/blob/38edd960b8ca2eb3421b24f40e77a1b96e16751a/test/scss/imports.scss#L6) for importing modules from paths starting with `~` which TravisCI also executes on Linux @mako-taco.

Could you come up with a small test repository which demonstrates the actual problem?

**Comment by mako-taco** [comment]
There were other (case insensitive) file system issues at play. Sorry for the false alarm.

**Comment by ceram1** [comment]
@jhnns But travis build seems not activated. 
https://travis-ci.org/jtangelder/sass-loader/builds

**Comment by ceram1** [comment]
Additional note:

@import 'node_modules/react-toolbox/lib/_colors';
Works fine, when @import '~' errors.
```
 @import '~react-toolbox/lib/commons';
           ^
          File to import not found or unreadable: ~react-toolbox/lib/commons
```

**Comment by jhnns** [comment]
@ceram1 Yep, I'm sorry. I was wrong. Travis CI is not activated because I'm not the owner of the repo. I use it in all my projects.

Concerning your feedback:
`'node_modules/react-toolbox/lib/_colors'` is another file than `'~react-toolbox/lib/commons'` :grin:. I'm pretty sure that this error is somehow related to your specific setup.

**Comment by ceram1** [comment]
That's right.. maybe ```resolve.alias```? I'm not sure what was it but react-toolbox-example runs well

**Comment by NogsMPLS** [comment]
having the same issue with alias in webpack not connecting with ```~moduleName``` in sass-loader.

**Comment by jhnns** [comment]
Could you provide an example?

**Comment by NogsMPLS** [comment]
the easiest thing I can point to right now is just cloning down react-toolbox repo and npm install both the main repo and the docs folder. then npm build inside the docs folder.

I'm digging as much as I can, but I'm not too familiar with this kind of thing yet.

**Comment by lencioni** [comment]
I'm digging into this a little more today. Here are some more details.

My `modulesDirectories` configuration looks something like this:

```js
modulesDirectories: [
  'app/assets',
  'app/assets/javascripts',
  'app/assets/stylesheets',
  'node_modules',
  'spec/javascripts',
],
```

The only file I can find that I have named `config` is at `app/assets/stylesheets/_config.scss`. But anyway, to make sure that I am using a more unique name, I changed this to `app/assets/stylesheets/_joe_config.scss`.

With sass-loader 2.0.0+ (currently running 3.1.1) a .scss file with the following line:

```scss
@import '~joe_config';
```

Results in the following error:

> File to import not found or unreadable: ~joe_config

Similarly, the following don't work:

```scss
@import '~_joe_config';
```

```scss
@import '~joe_config.scss';
```

```scss
@import '~stylesheets/joe_config.scss';
```

```scss
@import '~stylesheets/joe_config';
```

But the following seem to work:

```scss
@import '~_joe_config.scss';
```

```scss
@import '~stylesheets/_joe_config';
```

```scss
@import '~stylesheets/_joe_config.scss';
```

Does this make sense to you? Any help to point me in the right direction would be really appreciated.

**Comment by jhnns** [comment]
[`resolve.modulesDirectories`](http://webpack.github.io/docs/configuration.html#resolve-modulesdirectories) should only contain folder names, no actual paths. Webpack applies node's resolving algorithm with these folder names. It walks up the directories and tries each folder name:

```
a/b/node_modules
a/node_modules
node_modules
```

What you probably want is [`resolve.root`](http://webpack.github.io/docs/configuration.html#resolve-root) (which takes absolute paths!).

Btw: That's why `bower_components` should be listed as `resolve.root` instead of `modulesDirectories`

Please set up a small example repo (using `resolve.root`) which demonstrates the problem. It makes debugging at lot of easier for me and it may help you pinning down the problem, if it's in your configuration.

**Comment by lencioni** [comment]
Thanks! That was very helpful. I took the opportunity to improve the [documentation for `resolve.root` a little](https://github.com/webpack/docs/wiki/configuration#resolveroot).

I'm going to call this resolved. Thanks for the help and for the great work on this loader.

**Comment by jhnns** [comment]
You're welcome :grin:
