### ISSUE TITLE
Instructions regarding source maps are incorrect

### ISSUE THREAD

**Issue by WishCow** [jtangelder/sass-loader#150]
The README says that you have to use the extract-text-webpack-plugin to get source maps working, however that is not entirely correct. You *can* get it working that way, but that will make it impossible to get livereload (or hmr) working.

After following the conversion in a closed ticket webpack/extract-text-webpack-plugin/issues/30, @sokra said that the extract-text plugin is not supposed to be used in development. If you want to get sourcemaps working, you just have to add ?sourceMap to both the css loader, and the scss loader, like this:

```js
{
  test: /\.scss$/,
  loaders: [ 'style', 'css?sourceMap', 'sass?sourceMap' ]
}
```

This will allow both live reloading, and sourcemaps to work, without involving the extract-text plugin at all. It does have a bit of a weird file name in Chrome, but clicking on it takes you to the correct file and line number. From my rudimentary testing, the value of the "devtool" flag doesn't seem to effect the generated sourcemaps at all, it works for me with both "eval", "source-map".

![chrome sourcemaps](https://cloud.githubusercontent.com/assets/969284/9315868/14608426-4532-11e5-941f-a499c226766e.png)

**Comment by web2style** [comment]
When I use autoprefixer-loader it produces even more weird source path:

![zsfjq6z](https://cloud.githubusercontent.com/assets/2179726/9487925/a5d2461c-4bde-11e5-9891-50426a6f42b7.png)

Here is my webpack config:

```
var AUTOPREFIXER_BROWSERS = '"ie >= 10","ie_mob >= 10","ff >= 30","chrome >= 34","safari >= 7","opera >= 23","ios >= 7","android >= 4.4","bb >= 10"';

loaders: [
  "style-loader",
  "css-loader?sourceMap",
  "autoprefixer-loader?{browsers:[" + AUTOPREFIXER_BROWSERS + "]}",
  "sass-loader?sourceMap"
]
```

**Comment by web2style** [comment]
@jhnns, could you please explain what did you change to resolve the issue with source maps paths?

**Comment by jhnns** [comment]
The weird paths are created by the css-loader. Take a look at my [PR](webpack/css-loader#154) for further information.

**Comment by web2style** [comment]
@jhnns, your link points to 404 page.

**Comment by jhnns** [comment]
https://github.com/webpack/css-loader/pull/154

**Comment by web2style** [comment]
Thank you, it works perfectly for me!
