### ISSUE TITLE
importing css files, is sass-loader doing it? is it the right thing to do?

### ISSUE THREAD

**Issue by kswope** [jtangelder/sass-loader#154]
I got tripped up for a while because I had these lines in my app.scss

```
@import url('https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/css/bootstrap.min.css');

.btn-error {
  @extend .btn;
  cursor: default; // remove finger
  color: red;
}
```

Everything about the site worked just fine except @extend .btn didn't do a thing.

Bootstrap was displaying properly.

Took me a while to track down the fact that sass ignores importing files that don't have the extension sass or scss.  I only found this problem running my scss through the command line sass program.

So whats happening here is that sass-loader is importing a .css file but sass is ignoring it!  Or is another loader importing it?

Here's the relevant part of my config

```
      loaders: [
        {
          test: /\.scss$/,
          loader: "style!css!sass"
        },
        {
          test: /\.jsx?$/,
          loaders: [ 'react-hot', 'babel' ],
          exclude: /node_modules/
        },
        {
          test: /\.jsx?$/,
          exclude: /node_modules/,
          loader: 'babel-loader',
          query: {
            stage: 1
          }
        },
        {
          test: /\.css$/,
          loader: "style!css"
        }, 
        {
          test: /\.woff($|\?)|\.woff2($|\?)|\.ttf($|\?)|\.eot($|\?)|\.svg($|\?)/,
          loader: 'url-loader'
        }
      ]

```

**Comment by jhnns** [comment]
Sass is not downloading files afaik. So when you import an http url you won't be able to extend classes that are defined in these remote files. These imports will be resolved on runtime inside the browser.
