### ISSUE TITLE
Importing many files stalls indefinetly on large project

### ISSUE THREAD

**Issue by MikaAK** [jtangelder/sass-loader#159]
At work, we have a very large project which I'm converting our old project into webpack format. At a certain point though a number of sass files hang the build process and it never completes. 

I've managed to find the exact `import 'whatever.scss'` that causes the build to stop. Commenting it out will allow the build to complete (albeit very slow) but when commented in it freezes. I've increased the `UV_THREADPOOL_SIZE` to `800` but it doesn't seem to work. I remember having this issue which was part of #62 or #100. 

Each file has an import statement at the top to import variables `@import '~shared/styles/utility';` 
Is this due to the imports? If so how can I get this to work without stalling!

**Comment by MikaAK** [comment]
Removing the `UV_THREADPOOL_SIZE` solved this. I'm not entirely sure why

**Comment by Moghul** [comment]
You just saved 2 days of work, 2 years after the fact.
