### ISSUE TITLE
using the "functions" option of node-sass, not possible?

### ISSUE THREAD

**Issue by mkoryak** [jtangelder/sass-loader#160]
I need to use the following node-sass feature:
https://github.com/sass/node-sass#functions--v300---experimental

I cannot pass a function into the query string, is there any way I can do this without forking the project?
If a fork is required, how would you implement this? I will make a PR, and would love to know what I can do for it to be merged

**Comment by jhnns** [comment]
Will be shipped with #152, I just need to write tests for it.
