### ISSUE TITLE
Possible to only load appropriate .scss files?

### ISSUE THREAD

**Issue by tkiethanom** [jtangelder/sass-loader#161]
Is it possible to only load the appropriate .scss files? For some reason even though a react component isn't being used on a page the .scss file is still being included in my css.

I am currently using `ExtractTextPlugin` since I also want sourcemaps to work.

**Comment by jorrit** [comment]
Are you `require`-ing the React component and not using it?

**Comment by tkiethanom** [comment]
I don't think so. The component should only be pulled in when a certain page is hit.

So the question is. Is this normal or I am doing something wrong? Should the .scss only be loaded for the page you are on?

**Comment by jorrit** [comment]
Can you post some of your code? Otherwise it can't be established if you're doing something wrong. Is the code in a public repository?

**Comment by tkiethanom** [comment]
https://github.com/tkiethanom/splice/tree/sp2_front_end?files=1

Thanks for the help

**Comment by jorrit** [comment]
It is a large repository. Which file should not be included and in which files is it referenced? What command should I run to test it?

**Comment by tkiethanom** [comment]
In the /front_end directory there are some directions in the readme. Basically `npm install` and `gulp serve`.

**Comment by tkiethanom** [comment]
So for example if I put require('../../styles/accounts/accounts.scss'); in /src/pages/AccountsViewPage.js, The .scss still get loaded even if I'm on the home page.

**Comment by jhnns** [comment]
Webpack puts *all* required files into one big js file by default. If you want to load code (like styles) on demand, you need to create a [code split point](http://webpack.github.io/docs/code-splitting.html) by using an async require (will be `System.import` in Webpack 2).

This issue is not a sass-loader thing, though.
