### ISSUE TITLE
Publish a beta version for node-sass 3.4.0beta1

### ISSUE THREAD

**Issue by Phoenixmatrix** [jtangelder/sass-loader#163]
node-sass came out with a beta version, [v3.4.0-beta1](https://github.com/sass/node-sass/releases/tag/v3.4.0-beta1). The performance improvements are massive, and for a lot of uses cases, it's perfectly usable in its beta form.

The peerDependencies definition of sass-loader don't allow installing it though without tweaking its package.json, but sass-loader works perfectly fine with the beta if you force it to install.

Would it be possible to push out a sass-loader 2.0.1beta or something that allows node-sass v3.4.0beta1 in package.json while we wait for the real release, for convenience?

**Comment by Avien** [comment]
+1

**Comment by jhnns** [comment]
Mhmm you should be "allowed" to install that beta... is this a npm issue?

**Comment by Phoenixmatrix** [comment]
Its no longer needed since node-sass 3.4 is now released.

That being said: no, you would not be able to install 3.4beta. You can't even force it really (without manually modifying sass-loader's package.json.

carret notations (or really, any of the wildcard versioning for NPM) will only work with numeric X.Y.Z versions. To allow betas, you have to specifically do something such as `"^3.2.0 || 3.4.0-beta1"` as the version.

Anyhow, this no longer matters, so Ill close :)

**Comment by jhnns** [comment]
@Phoenixmatrix Thx for informing me :+1:

**Comment by Avien** [comment]
Yep, tx!!
