### ISSUE TITLE
[Q] Is there a way to implicitly `import` some shared .scss files globally?

### ISSUE THREAD

**Issue by tizmagik** [jtangelder/sass-loader#172]
So I have a `/common/_variables.scss` that defines some theme colors and such and I'd really rather not have an `@import 'common/variables` at the top of every single SCSS file that needs it. Is there any way around this currently?

**Comment by jhnns** [comment]
Just put `@import 'common/variables'` at the beginning of your `main.scss` and everything should be fine.

However, I don't get why you would like to have implicit imports/globals. Modular,re-usable code declares its dependencies explicitly.
