### ISSUE TITLE
Loading images inside sass

### ISSUE THREAD

**Issue by webchaz** [jtangelder/sass-loader#175]
This may not be specific to sass-loader, or maybe it is, but I'm trying to load images into sass files.  Any suggestions on a good way to do this? I've tried [file-loader](https://github.com/webpack/file-loader) and [url-loader](https://github.com/webpack/url-loader) but didn't seem to do anything.  Is there a way within sass loader that's recommended for using images?

Thank you

**Comment by jhnns** [comment]
The sass-loader does not resolve `url()` statements in your styles. You should chain the css-loader as described in the README.

Also take a look at the section about `url()` in the README.

**Comment by JesusisFreedom** [comment]
@jhnns What about a situation where you arent using the css-loader I.E. Angular 2 where you need to run. 
`
      {test: /\.(woff|eot|ttf|svg)$/, loader: 'file-loader?name=assets/[name].[ext]?[hash]'},

      {
        test: /\.scss$/,
        loaders: ['raw-loader', 'postcss-loader', 'resolve-url-loader', 'sass-loader?sourceMap']
      },
`

**Comment by jhnns** [comment]
I don't know. Why aren't you allowed to use the css-loader with Angular 2?

**Comment by sliker** [comment]
@jhnns I have the problem that @austbot mention; I can't use css-loader because angular styles receive an array of strings so it generates an error when try to render if you use it, and if you don't use it the sass loader don't handle the url images and assets of component styles.

**Comment by jhnns** [comment]
You could try to use the [extract-loader](https://github.com/peerigon/extract-loader), it evaluates a CommonJS module to generate a string. Chain the loaders like this:

```
  {
    test: /\.scss$/,
    loaders: ['extract-loader', 'css-loader', 'sass-loader']
  },
```

**Comment by sliker** [comment]
@jhnns extract-loader fail's on line 1 of the first scss, I just have an import on that line ´@import "../../../sass/variables";´
I use the loaders exacts as you put it.

**Comment by jhnns** [comment]
That sounds like the sass-loader is not applied. The css-loader should not see any Sass imports.

Also, the error would be helpful.

**Comment by Hufschmidt** [comment]
To use the css-loader with Angular2's @Component-Decorator styles use this loader-chain:
`exports-loader?module.exports.toString()!css-loader!sass-loader`
this will allow you to do:

    @Component({
      selector:   'bar-foo',
      template:   require('./foo.template.html'),
      styles:     [ require('./foo.template.scss') ]
    })
    export class FooComponent {
        ...
    }

or this load-erchain for global styles, like ionic-angular or fonts-awesome:
`style-loader!css-loader?sourceMap!resolve-url?sourceMap!sass-loader?sourceMap`
(resolve-url is required if you don't want to set font-path's and such manually)

**Comment by jhnns** [comment]
Thx for sharing.
