### ISSUE TITLE
bug: sass-loader can't load one sass file twice

### ISSUE THREAD

**Issue by niluanxy** [jtangelder/sass-loader#184]
I use webpack in my project and use sass to write css. Then i split common code like person-box in common/person-box.scss.And when i use this css,i only need @import common/person-box.scss.but i found when i import twice,it will can't build sass file.For example,in user page and person page,i all use pserfon-box css,if i only import in user page's sass file,it can build.if i use and in person page,when i build,it will pend.i use webpack in gulp.

**Comment by eMaj-Fr** [comment]
same error.

**Comment by niluanxy** [comment]
I fix it by require has builded scss file,old: require("style.scss"),now: require("style.css"),and style.css file is build by other task of style.scss file.

**Comment by jhnns** [comment]
I don't get the question but I doubt that this is actually a bug of sass-loader.
