### ISSUE TITLE
Mention indentedSyntax in the README.md

### ISSUE THREAD

**Issue by Kadrian** [jtangelder/sass-loader#187]
I was very clueless, after I got an error, when I was trying to compile sass instead of scss.
`Invalid CSS after "": expected 1 selector or at-rule, was "body"`

So I think you would help a couple of people if you'd just mention in the Readme, that:

"In case you want to work with sass and not scss, add the indentedSyntax option".

Keep up the good work :)

**Comment by mr-wildcard** [comment]
+1

**Comment by alannesta** [comment]
+1, I got the same error and this PR saves my life

**Comment by alex88** [comment]
+1 Just had the same issue! A must have in the readme!

**Comment by iabdulin** [comment]
+1

**Comment by mattma** [comment]
+1 works as magic.

**Comment by zhulongzheng** [comment]
+1 It saves me!

**Comment by jhnns** [comment]
Starting with [sass-loader `3.2.0`](https://github.com/jtangelder/sass-loader/releases/tag/v3.2.0), you don't need to set it explicitly. It will derive it from the file name.

**Comment by tiiger** [comment]
I use sass-loader 4.0.2 but have the same error. I'm not sure what I should do now... :/

**Comment by apieceofbart** [comment]
@tiiger 
I am using 5.0.0 but still had to add `indentedSyntax=true`. Check this line from `webpack.config.js` (webpack 1.14):
`loaders: ["style-loader", "css-loader", "sass-loader?indentedSyntax=true"]`

Without this I still got "Invalid CSS.." error

**Comment by jhnns** [comment]
Do you use the `.sass` file extension? Can you please provide a small test case that demonstrates the problem?

**Comment by apieceofbart** [comment]
I am using `.scss`. If I use `.sass` loader doesn't work: 

```
ERROR in ./app/components/ChangeOrderButton.sass
Module parse failed: /some/path/here/app/components/ChangeOrderButton.sass Unexpected token (1:0)`You may need an appropriate loader to handle this file type.
```
Maybe it's a different issue. I will create small test case whenever I have time.

**Comment by apieceofbart** [comment]
Ok, turns out it was my fault - I was testing for `.scss` not `.sass` files in webpack config. Sorry for the trouble!

**Comment by atilkan** [comment]
You can test both:
`test: /\.s[ac]ss$/,`
