### ISSUE TITLE
Question: using sass-loader with lint loader

### ISSUE THREAD

**Issue by alexisinwork** [jtangelder/sass-loader#188]
Hi!
Thanks for great module.
Got a question related to using this along with linter - any pointers?
Wanted to use something that won't depend on Ruby & ended up with http://github.com/alleyinteractive/sasslint-loader but ran into issue:
my config is following:
```
      {
        test    : /\.scss$/,
        loaders: [
          'style-loader',
          'css-loader',
          'autoprefixer-loader',
          'sasslint',
          'sass-loader?includePaths[]=' + paths.project("node_modules/compass-mixins/lib") +
          "&includePaths[]=" + paths.src("styles")
        ]
      },
```
But it's running after original files were bundled & thus links to lines that are not present in original files that have all the `imports`.

**Comment by dmachat** [comment]
Just stumbled across this issue. Definitely a bug in the linter, sorry (https://github.com/alleyinteractive/sasslint-loader/issues/4). We're actively working on it this week, so keep an eye out.
