### ISSUE TITLE
Load image from partial file, compiled twice. Bug or Not ?

### ISSUE THREAD

**Issue by CodeRiderz** [jtangelder/sass-loader#197]
Hi, 
I was trying to create partial files and put it in child directory.
I use ```url-loader```, and use ```@import "..."```, but why it returns error ? 
It happened because the css compiled twice : partials file and file which importing it.
If we put it on different file, one of them will returns an error because the path is wrong. 
But if it's on the same directory, that works fine.
Is it a bug ?

**Comment by jhnns** [comment]
Please use Stackoverflow for questions using the webpack tag. This way, a much larger user-base is able to benefit from the answer and there are more people how actually answer it. If this is a bug report, please provide a small example project.
