### ISSUE TITLE
The `libsass` binding was not found looking in win32-ia32-11 but actually in win32-x64-46

### ISSUE THREAD

**Issue by mattwhetton** [jtangelder/sass-loader#201]
I'm getting the following error trying to run on a windows x64 machine:

    Error: The `libsass` binding was not found in project\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-ia32-11\binding.node

The "win32-ia32-11" directory doesn't exist, but the "win32-x64-46" does, and has the binding.node folder in it.

Is this a bug or is there some way to resolve it?

Matt

**Comment by mattwhetton** [comment]
Ok, so just found this article which resolves my issue: http://blog.boro2g.co.uk/grunt-and-gulp-tasks-in-visual-studio-2015-libsass-error/

**Comment by jhnns** [comment]
Thx for sharing
