### ISSUE TITLE
i got a empty object when import a sass file.

### ISSUE THREAD

**Issue by Burhh** [jtangelder/sass-loader#206]
hi, brother. i saw many tutorial import css file like this:
```
import React, { PropTypes, Component } from 'react'
import styles from './index.css'

console.log(styles)
export default class PageLoading extends Component {
  render() {
    return (
      <div className={styles.loading}>Hello page loading!</div>
    )
  }
}
```
please attention the className is expression.
but when i import sass by same way. i found i can't use the styles.loading in className

```
import React, { PropTypes, Component } from 'react'
import styles from './index.scss'

console.log(styles)
// styles is a empty object
export default class PageLoading extends Component {
  render() {
    return (
      <div className={styles.loading}>Hello page loading!</div>
    )
  }
}
```

how can i resolve it. thank u.!

**Comment by Multiply** [comment]
I get the same thing. Styles actually do work if you reference the direct className from the scss file, but the object is empty, regardless.

**Comment by Multiply** [comment]
If you configure it like this, it seems to work: ```json
{
	test: /\.scss$/,
	loader: 'style!css?modules!sass'
}
```

**Comment by raphaguasta** [comment]
@Burhh It Worked for you? Same problem here. Does not work for me.

**Comment by Burhh** [comment]
@Multiply  thank u for your reply.Please forgive me for not timely reply,this config is work for me .thx

**Comment by Burhh** [comment]
@raphaguasta hi, it's work for me . i think the problem lies in the loader config's arrangement order

**Comment by raphaguasta** [comment]
Im not sure what the problem was, but i remade the project and it worked. Thanks! :)

**Comment by raphaguasta** [comment]
Thanks, @Burhh !

**Comment by silvenon** [comment]
This is not a sass-loader issue, you just forgot to turn on CSS Modules in the css-loader.

**Comment by Drumstix42** [comment]
For anyone else finding this topic years later, the CSS Modules config is important as noted in the previous comment. Check out: https://github.com/webpack-contrib/sass-loader/issues/206

The simple fix, without really needing to adjust the default `modules` config for `css-loader` is to put `.module.` into your file name. E.g.: `_exports.module.scss`

**Comment by ibocon** [comment]
> This is not a sass-loader issue, you just forgot to turn on CSS Modules in the css-loader.

```
module.exports = {
  module: {
    rules: [
      {
        test: /\.scss$/i,
        use: [ 
          "style-loader", 
          {
            loader: "css-loader", 
            // setting 'compileType' to "icss" sovled my problem..
            options: { modules: { compileType: "icss" }}
          }, 
          "sass-loader"
        ],
      },
}
```

**Comment by hadasmaimon** [comment]
resourse:
 https://www.bluematador.com/blog/how-to-share-variables-between-js-and-sass

make sure you installed that:
npm install sass-loader node-sass webpack --save-dev
