### ISSUE TITLE
Custom functions docs

### ISSUE THREAD

**Issue by glebmachine** [jtangelder/sass-loader#210]
Hi!

I found awesome part of `sass-loader` in tests folder: https://github.com/jtangelder/sass-loader/blob/master/test/tools/customFunctions.js

You definitely should share this to the world.
Please, add description to the docs

**Comment by glebmachine** [comment]
I have found this feature right from libsass, sorry.
But still, can you describe sassLoader options object please?)

**Comment by jhnns** [comment]
There are a lot of features from node-sass/libsass that one should take a look at. We just pipe all the options through, so I only added notes on options that might be webpack specific. If you feel like this is important, please create a PR.

**Comment by MichaelIT** [comment]
@glebmachine 
Hi, this is not a problem on sass-loader, it was related to webpack options config.
If u want to pass custom functions to node-sass, u may want to define `ident ` in webpack config.
 https://webpack.js.org/guides/migrating/#complex-options

```
{
      test: /\.scss$/,
      exclude: /node_modules/,
      use: [{
        loader: 'style-loader'
      }, {
        loader: 'css-loader'
      }, {
        loader: 'sass-loader',
        options: {
// ========add flowing line
          ident: "by-michael",
          functions: {
            customfunction(color, index) {
              return sassTypes.String(color.getValue());
            },
...
```

**Comment by glebmachine** [comment]
Yeah, thanks!
But, i have moved to stylus(

**Comment by MuYunyun** [comment]
I think it's necessary to prompt what features can be used in the options.:smile:
