### ISSUE TITLE
Webpack 2 support?

### ISSUE THREAD

**Issue by mike-engel** [jtangelder/sass-loader#214]
Hey, just wanted to check on either plans or work being done to support webpack 2. It's currently in what seems to be in a late stage beta, and I'm unable to install sass-loader due to the `peerDependency`. Thanks!

**Comment by thuringia** [comment]
@mike-engel Are you still using npm@2? With npm@3 this is not an issue anymore.
Sass-loader appears to be working fine with webpack 2, unfortunately I have not done any extensive testing yet.

**Comment by mike-engel** [comment]
@thuringia yeah, we're still using node v4.3, which defaults to npm v2 (and we need to support the default for now).

**Comment by zachrip** [comment]
@mike-engel You can upgrade NPM independently of Node - I have the same constraint at work (staying on stable node branch). I use Webpack2 and Sass-Loader.

**Comment by xlc** [comment]
I am using npm3 but getting this error when running `npm shrinkwrap --dev`
If sass-loader is indeed compatible with webpack2, the dependency should be `webpack": "^1.12.6 || ^2.1.0-beta`

>npm ERR! peer invalid: webpack@^1.12.6, required by sass-loader@3.2.0

**Comment by mike-engel** [comment]
@zachrip I'm aware that this works with npm 3. I do, however, need to support npm 2 as I mentioned earlier.

**Comment by axelson** [comment]
@zachrip what did you have to do to get this working? I'm running into problems getting the sass loader to load. Very possibly a configuration issue with upgrading to webpack2 though.

**Comment by zachrip** [comment]
@axelson Can you please post your config? (Also, you've done a reinstall of your modules yeah?)

**Comment by michaelmelanson** [comment]
I'm getting a peer dependency error: `npm ERR! peer invalid: webpack@^1.12.6, required by sass-loader@3.2.0`

We have `webpack@2.1.0-beta.7` installed. It looks like the peer dependency for `sass-loader` needs to be updated to allow Webpack 2.0.

I'm seeing this on node v6.0.0 and npm v3.8.6.

**Comment by jhnns** [comment]
The sass-loader works with webpack 2. I've added it to `peerDepedencies` starting with `3.2.1`.
