### ISSUE TITLE
Is there any way to remove comments from scss files upon compilation?

### ISSUE THREAD

**Issue by jkyoutsey** [jtangelder/sass-loader#219]
Comments are bits I just don't want to serve up across the wire.  Is there any config I can use to remove all comments from the generated results?  Minification would be good too.

**Comment by jhnns** [comment]
Using webpack 1: If you add the [`UglifyJsPlugin`](http://webpack.github.io/docs/list-of-plugins.html#uglifyjsplugin) to your webpack config, it will switch all loaders into minimize mode.
Using webpack 2: Now you are able to switch only specific loaders into minimize mode by using the LoaderOptionsPlugin.

Related discussion: https://github.com/webpack/webpack/issues/283

**Comment by wzup** [comment]
Regarding `LoaderOptionsPlugin`. Tutorial [says](https://webpack.js.org/plugins/loader-options-plugin/):

> This plugin will be removed in the future as it only exists for migration.

Do you have any info already about what to use instead?

**Comment by evilebottnawi** [comment]
@wzup use `options` property in loader
