### ISSUE TITLE
How easy to use image root without ../../../home/1.jpg, I want to home / 1.jpg

### ISSUE THREAD

**Issue by janjon** [jtangelder/sass-loader#220]
How easy to use image root without ../../../home/1.jpg, I want to home / 1.jpg

**Comment by elektronik2k5** [comment]
@janjon you need to add `1.jpg`'s path to webpack's `module_directories` then use it like so `~1.jpg`.

**Comment by jhnns** [comment]
@janjon @elektronik2k5 Please don't use the `modules_directories` option for this. `resolve.root` is better for this purpose. `module_directories` will traverse all folders up to `/` similar like node does with `node_modules`.
