### ISSUE TITLE
ExtractTextPlugin isn't compiling sass

### ISSUE THREAD

**Issue by Jmeyering** [jtangelder/sass-loader#221]
When using HMR and the dev-server i have the following loader setup.

```
          {
              test: /\.s?css$/,
              loaders: ["style", "raw", "sass?sourceMap"]
          },
```

This works great, my page is hot reloading and everything.

For production i wanted to extract the generated css into its own file, so I changed my production loader to use.

```
        {
            test: /\.s?css$/,
            loader: ExtractTextPlugin.extract("style", "raw", "sass")
        }
```

ExtractText seems to be pulling my sass out, but I only get my first file, none of the @include statements are pulled in via sass. It seems as though sass doesn't get a chance to compile the file.

Any thoughts on what I am doing wrong?

**Comment by elektronik2k5** [comment]
@Jmeyering , I believe you need to remove the `style` loader from the prod config. `raw` loader isn't necessary in both configs too.

**Comment by gbahamondez** [comment]
The same for me, any ideas?

**Comment by Jmeyering** [comment]
I never got it to work at all. I switched to extract-loader
https://github.com/jtangelder/sass-loader

**Comment by samjacoby** [comment]
I don't think is related to sass-loader. The issue is in how options are being passed to the plugin:

Something like any of the below should work: 
````javascript
ExtractTextPlugin.extract("style", "!raw!sass")
ExtractTextPlugin.extract("style", ["raw", "sass"])
````
The key is defining the initial loader separately.

**Comment by Jmeyering** [comment]
That's perfect! Thanks so much for the tip!
