### ISSUE TITLE
Sourcemap breaks when using @import in a wrapper

### ISSUE THREAD

**Issue by Dagniele** [jtangelder/sass-loader#222]
I have this problem, i am trying to generate the sourcemap for a style.scss file which imports other files inside a wrapper.

Example:
.my-container {
    @import "bootstrap-from-somewhere";
}

In this case my sourcemap will have for reference always the line with .my-container.

If I remove the container and just import in the root, the sourcemap works fine.

Is this a bug or am I doing something wrong?

**Comment by jhnns** [comment]
This sounds like an issue in node-sass. We just get the complete source map from node-sass.
