### ISSUE TITLE
Sourcemaps have incorrect relative path when using webpack-dev-server

### ISSUE THREAD

**Issue by dolly22** [jtangelder/sass-loader#223]
webpack-dev-server always resets config.output.path to `/`. That causes strange urls to appear in generated sourcemap.

`"/./styles/main.scss"` - generated when using webpack
`"/./styles/Projects/webpack-sass/styles/main.scss"` - generated when using webpack-dev-server (assuming project is located in c:\Projects\webpack-sass)

https://github.com/jtangelder/sass-loader/blob/e81fa62974556049fc5063c11089fb97581d9410/index.js#L224-L227

**Comment by jhnns** [comment]
Does [this PR](https://github.com/jtangelder/sass-loader/pull/250) fix your problem (install sass-loader `3.2.2`)?

**Comment by jhnns** [comment]
Should be fixed with #374
