### ISSUE TITLE
Cannot find module @3.2.0

### ISSUE THREAD

**Issue by xiaoyunchen** [jtangelder/sass-loader#225]
Here is my source code :
`import "./titlebar.scss";`

and the webpack-config:
`
loaders: [	
        	{
                test: /\.js?$/,
                loader: 'babel',
                query: {
                  presets: ['es2015']
                }
            },
            {test: /\.css$/, loader:'style-loader!css-loader' },
            {test: /\.scss$/, loaders: ["style", "css", "sass"] },	//sass
            {test: /\.html$/, loader: "html" },
            {test: /\.(png|jpg)$/, loader: 'url-loader?limit=8192&name=./img/[hash].[ext]'}
        ]
`

and the output file error like this :
`
// load the styles
	var content = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"!!./../../../node_modules/css-loader/index.js!./../../../node_modules/sass-loader/index.js!./titlebar.scss\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
`

Any ideas or missed something important?

**Comment by Tux1** [comment]
I don't think that it's the same issue.
In my case, I have to prepend the path with `~` when I use webpack alias.
For example, I have the alias : `assets: '/app/assets/'` so when I want to import a file in `assets` I have to do that : `@import "~assets/toto.scss"

**Comment by mattxo** [comment]
I'm having what appears to be a similar issue. Do you manage to fix it? @xiaoyunchen 

```
 Asset       Size  Chunks             Chunk Names
9:07 PM -    js/app.12ffa852f5a419a52c5d.js    1.55 MB       0  [emitted]  app
9:07 PM - js/vendor.12ffa852f5a419a52c5d.js     457 kB       1  [emitted]  vendor
9:07 PM - js/common.12ffa852f5a419a52c5d.js     890 kB       2  [emitted]  common
9:07 PM -                        index.html    1.33 kB          [emitted]  
9:07 PM -                   img\favicon.ico    5.43 kB          [emitted]  
9:07 PM -          img\shield-with-beta.png    21.3 kB          [emitted]  
9:07 PM -                 service-worker.js   43 bytes          [emitted]  
9:07 PM -                        stats.json  178 bytes          [emitted]  
9:07 PM -  [673] ./src/shims/shims_for_IE.js 6.74 kB {1} [built]
9:07 PM -        ... -> factory:157ms building:156ms
9:07 PM -     + 715 hidden modules
9:07 PM - ERROR in ./~/css-loader?sourceMap!./~/postcss-loader!./~/sass-loader!./~/raw-loader!./~/postcss-loader!./~/sass-loader!./src/[censored]/style.scss
9:07 PM - Module build failed: 
9:07 PM - @import "./../../../style/[censored].scss";
9:07 PM -              ^
9:07 PM -       Invalid CSS after "module.exports": expected "{", was '= ".difficulty-sele'
9:07 PM -       in c:\src\[censored]\style.scss (line 1, column 15)
9:07 PM -  @ ./src/[censored]/style.scss 4:14-341
```

**Comment by mattxo** [comment]
I did manage to resolve my issue... I was accidentally importing a Component in Angular2 from outside the root of the project.

**Comment by jhnns** [comment]
Please use Stackoverflow for questions using the webpack tag. This way, a much larger user-base is able to benefit from the answer and there are more people how actually answer it. If this is a bug report, please provide a small example project.
