### ISSUE TITLE
Webpack aliases not working with @import

### ISSUE THREAD

**Issue by Tux1** [jtangelder/sass-loader#226]
Hi,

It seems I found a bug with webpack aliases import. Even if you specify a alias correctly, sass-loader doesn't find the file and throw an compilation error.

I made a simple project to help :
https://github.com/Tux1/examplesasserror

**Comment by Tux1** [comment]
The `~` was missing in the `@import` instruction

**Comment by xiaoyunchen** [comment]
Hi,I got the same problem #225 
could u please me a sample  of @import

**Comment by Tux1** [comment]
I don't think that it's the same issue.
In my case, I have to prepend the path with `~` when I use webpack alias.
For example, I have the alias : `assets: '/app/assets/'` so when I want to import a file in `assets` I have to do that : `@import "~assets/toto.scss"

**Comment by xiaoyunchen** [comment]
so any suggestion about #225 ?
