### ISSUE TITLE
Update peerDependencies for webpack 2

### ISSUE THREAD

**Issue by erwingaitano** [jtangelder/sass-loader#232]
Webpack 2 beta has been out for a while and this loader works fine with it. Can we update the peerDependencies to:

`"webpack": "^1.4.0 || ^2.1.0-beta"`

**Comment by sompylasar** [comment]
👍 please?

**Comment by sompylasar** [comment]
It has even got a PR: #233

**Comment by aight8** [comment]
+1

**Comment by Silviu-Marian** [comment]
+1

**Comment by ljwagerfield** [comment]
+1

**Comment by faddee** [comment]
+1

**Comment by jhnns** [comment]
Shipped with `3.2.1`
