### ISSUE TITLE
Need resourcePath in custom importer

### ISSUE THREAD

**Issue by jameslnewell** [jtangelder/sass-loader#234]
Because `stdin` is the value of `prev` in `function (url, prev, done)` my custom importer can't load files relative to the SCSS file `@import`ing another SCSS file.

Could the importers be wrapped something like this?

```javascript
sassOptions.importer = sassOptions.importer 
  ? [].concat(sassOptions.importer).map(function(importer) {
    return function(url, prev, done) {
      return importer(url, prev === 'stdin' ? resourcePath : prev, done); // <== replace 'stdin'
    };
  }
  : []
;
```

**Comment by jhnns** [comment]
That looks like a good idea! Can you create a PR + a small test-case for it? Just mention me in my PR and I will merge it asap.

**Comment by neverfox** [comment]
I can't be sure, but I think this breaks `this` inside of the custom importer. I'm not sure if that's a problem that should be solved in the importer or not, but see [here](https://github.com/Updater/node-sass-json-importer/issues/34) for context.

**Comment by jameslnewell** [comment]
`return importer.call(this, url, prev === 'stdin' ? resourcePath : prev, done);` should fix that I think
