### ISSUE TITLE
Add Node v6.0.0 support

### ISSUE THREAD

**Issue by Snabel** [jtangelder/sass-loader#241]
When using node v6.0.0 with node-sass and webpack i get the following error:

webpack --config webpack.config.dev.js --watch
Hash: 9e5059f15d2b9c2485b1
Version: webpack 1.13.0
Time: 1991ms
Asset Size Chunks Chunk Names
app.js 1.13 MB 0 [emitted] main
[0] multi main 28 bytes {0} [built]
+ 285 hidden modules

ERROR in Node Sass does not yet support your current environment: OS X 64-bit with false
For more information on which environments are supported please see:
TODO URL
@ ./src/style/main.scss 4:14-121

**Comment by alexanderchan** [comment]
See sass/node-sass#1504 and nodejs/node#6500 for further details on this.

**Comment by jhnns** [comment]
Close?

**Comment by alexanderchan** [comment]
For node6, upgrading to node-sass 3.7 resolved the problems I had (long error messages).
