### ISSUE TITLE
~ not resolving to root directory

### ISSUE THREAD

**Issue by synthecypher** [jtangelder/sass-loader#244]
I'm attempting to get to my base styles they're relative to the `context` directory specified in webpack's config ([link](http://webpack.github.io/docs/configuration.html#context)).

```
context
├── base
│   ├── _colors.scss
│   ├── _fonts.scss
│   ├── _layout.scss
│   └── _panel.scss
│   └── _colors.scss
└── admin
    └── components
        └── modal
            └── user
                └── preview
                    └── preview.scss
```

```sass
// preview.scss
@import "~base/colors"
.preview {
  color: $red
}
```

**Comment by jhnns** [comment]
Please use Stackoverflow for questions using the webpack tag. This way, a much larger user-base is able to benefit from the answer and there are more people how actually answer it. If this is a bug report, please provide a small example project.
