### ISSUE TITLE
TIP: Make sure your project path (folder names) does not contain "!" exclamation mark

### ISSUE THREAD

**Issue by IAMtheIAM** [jtangelder/sass-loader#247]
It took me a while to figure out why I the `test-source-map` script was failing, but it was because the path I installed this repo into contained a `!` which broke the other module loaders. It was like `c:\dev\!projects\sass-loader` - so that broke it. 

When I removed the `!` from the folder name, it works fine. Make sure your project path folder does not contain "!" exclamation mark

**Comment by jhnns** [comment]
I've never seen an exclamation mark in a path my whole life ^^
