### ISSUE TITLE
Example: Sourcemaps showing proper file name in Chrome

### ISSUE THREAD

**Issue by IAMtheIAM** [jtangelder/sass-loader#248]
Source maps is not properly working.

my config:

```
'use strict';

var path = require('path');

module.exports = {
    entry: './test/sourceMap/entry.js',
    output: {
        path: '../test/output',
        filename: 'bundle.sourcemap.js'
    },
    devtool: 'inline-source-map',
    module: {
        loaders: [
            {
                test: /\.scss$/,
                loaders: ['style', 'css?sourceMap', 'sass?sourceMap']

            }
        ]
    }
};

```
Chrome:
![no_sourcemaps](https://cloud.githubusercontent.com/assets/13709948/15402255/1ecc5b52-1da8-11e6-836f-fc8e92b27074.png)

FireFox
![firefox_sourcemaps](https://cloud.githubusercontent.com/assets/13709948/15402278/47aa685c-1da8-11e6-93d2-6c570f677b00.png)

Edge
![ie_sourcemaps](https://cloud.githubusercontent.com/assets/13709948/15402281/4bde5a82-1da8-11e6-8e5b-f51b825be27e.png)

**Comment by IAMtheIAM** [comment]
@web2style @luismreis @sokra  It is now possible to use angular2, webpack with hot module replacement, sass sourcemaps, and externally loaded css. It tooks me days of playing with it but I got it working!

The dependencies are `style-loader`, `css-loader`, and `sass-loader`.

![sass_sourcemaps _hmr _wds](https://cloud.githubusercontent.com/assets/13709948/15442737/ca3b41ca-1e97-11e6-9607-7f14bd311d84.png)

In your webpack config, you need this loader:

```
{
        test: /\.scss$/,
        exclude: /node_modules/,
        loader: 'style!css?sourceMap!sass?sourceMap&sourceComments'
}
```

Then, in your component, for example, app.component.ts, you would require your .scss file **OUTSIDE of the @Component decorator**. That is the trick. This will not work if you load styles the "angular2 way". Better to let webpack handle styles with lazy-loading anyway.

```
/*
 * THIS IS WHERE WE REQUIRE CSS/SCSS FILES THAT THIS COMPONENT NEEDS
 *
 * Function: To enable so-called "Lazy Loading" CSS/SCSS files "on demand" as the app views need them.
 * Do NOT add styles the "Angular2 Way" in the @Component decorator ("styles" and "styleUrls" properties)
 */
require('./app.scss');

/*
 * App Component
 * Top Level Component
 */
@Component({
  selector: 'app',
  pipes: [],
  providers: [],
  directives: [RouterActive],
  encapsulation: ViewEncapsulation.None,
  ],
  template: require('./app.html')
})
```

I have had no problems running this setup. Does anyone see a "problem" with doing this? If not, here you go!

**Comment by jhnns** [comment]
If you want to provide an example, go ahead and create a PR
