### ISSUE TITLE
Import css with url

### ISSUE THREAD

**Issue by slavik57** [jtangelder/sass-loader#253]
I import a css file with a font-face declared in it with a relative URL.
I use the raw-loader!sass-loader chain because it's an angular component style.

When I do that the content of the file is being copied to the file. And when I load the page it tries to load the fonts from a wrong directory.

The fonts work because I load them with different loaders chain in a different file. The chain is: css!resolve-url!sass?sourceMap

So the fonts are there but the issue is that the content of the css is copied twice...

Can I do something about it? So that the sass loader will know not to copy the css content?

**Comment by jhnns** [comment]
Please use Stackoverflow for questions using the webpack tag. This way, a much larger user-base is able to benefit from the answer and there are more people how actually answer it. If this is a bug report, please provide a small example project.
