### ISSUE TITLE
Allow "." in folder names when using includePaths[]=

### ISSUE THREAD

**Issue by sleepingevil** [jtangelder/sass-loader#255]
I'm using animate.css for certain animations on the site. I just set up includePaths to have absolute references to css and sass files when using the `@import` statement in sass. Sass-loader fails to work out the location of the imported file when the directory name has a "." in it.

Example:

Loader:

```
test: /\.scss$/,
  loaders: [
    'style-loader',
    'css-loader',
    'autoprefixer-loader',
    `sass-loader?outputStyle=compressed&includePaths[]=${path.resolve(__dirname, './styles')}&includePaths[]=${__dirname}`
  ]
```

My failing import statement:

`@import 'node_modules/animate.css/animate.min.css';`

Error message:

`Module not found: Error: Cannot resolve 'file' or 'directory' ./node_modules/animate.css/animate.min.css in /Users/[CENSORED]
[0]  @ ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader?outputStyle=compressed&includePaths[]=/Users/[CENSORED]/styles&includePaths[]=/Users/[CENSORED]!./[CENSORED].scss 3:10-112`

Note: this import is working fine: `@import 'node_modules/toastr/toastr.scss';`

Thanks!

**Comment by sleepingevil** [comment]
I realised that the whole concept of accessing node modules like this is wrong, since I can just import them like so:

`@import '~animate.css/animate.min.css'`

This one works even with the "." in the folder name. However, I still cannot import sass files through includePaths if the folder name has a "." in it.

**Comment by jhnns** [comment]
When using the query syntax, you must stick to regular URL escaping. So the official way would be:

```javascript
`sass-loader?includePaths[]=${encodeURIComponent(path.resolve(__dirname, './styles'))}`
```

Since this is stupid I always recommend to use `JSON.stringify()`

```javascript
`sass-loader?${JSON.stringify({
    compressed: true
    includePaths: [ ... ]
})}`
```

We know that configuring loaders is very complicated 😞 . We're currently working on that.

**Comment by sleepingevil** [comment]
Thanks for the JSON.stringify idea! ;)
