### ISSUE TITLE
ERROR in %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by junjchen** [jtangelder/sass-loader#258]
I was trying to setup sass-loader today and got this error in the console
```
ERROR in %1 is not a valid Win32 application.
```

Googled a bit seems it relates with python executable installed, so anyway I have Win8 64b + node 4.4.5 + python 2.7.9 on my machine.

Is there anything wrong with the setup or something, do you guys know?

**Comment by jhnns** [comment]
I doubt that this is an issue of the sass-loader. Do you have a stack trace or anything? We also need a **minimal** example that demonstrates the error.

**Comment by junjchen** [comment]
Hi @jhnns Thanks for the reply, as you said it was nothing to do on sassloader indeed =) , I got that solved some days after the issue report, somehow, but I forgot how =(

So I will just closing the issue now..
