### ISSUE TITLE
Global variables, are not recommended, but my @font-face seems to work 

### ISSUE THREAD

**Issue by ianjohnspain** [jtangelder/sass-loader#262]
Hi,

I have been trying to wrap my head around the non use of global sass variables when using the loader. I think this is great! Means I now have to explicitly @import my variables at the top of each file to be able to use them, i agree this is probably good practise. Everything seems to be working.

Although I have managed to get away with importing ONCE a @font-face and it seems to be working. I was hoping to understand why @font-face i can load once at the start and is available to all sass files but my _variables, for example, I need to @import these in each sass file i wish to use ?

I have _fonts.scss file that I import once and it seems to be available in all other scss files... here is my import for my fonts

```
@import 'bourbon';

@include font-face('Lato Regular', '../fonts/test-webfont', $file-formats: woff);
```

Thanks for any help in advance.

**Comment by jhnns** [comment]
Funnily, I've dealed with the same problem yesterday and that's how I tackled it. First you need a `export-once` function:

```sass
$export-once-names: ();

@function export-once($name) {
    @if index($export-once-names, $name) {
        @return false;
    }
    $export-once-names: append($export-once-names, $name) !global;
    @return true;
}
```

You should use that function for all sass code that actually outputs CSS to ensure that no duplicates are added to the final stylesheet.

Than you have a mixin to create the `font-face` declaration. I've removed some code that might be implementation dependent:

```sass
@mixin font-face($family, $weight: regular, $style: normal, $stretch: normal) {

    @if export-once("font-face-#{$family}-#{$weight}-#{$style}-#{$stretch}") {
        // make sure the declarations will not be nested
        @at-root {
            @font-face {
                ...
            }
        }
    }
   
}
```

Then you have a mixin which applies a `font-family` and all its respective values to an element

```sass
@mixin font-helvetica() {
    @include font-face("Helvetica Neue");

    font-family: "Helvetica Neue", sans-serif;
    font-weight: regular;
    font-style: normal;
    font-stretch: normal;
}

@mixin font-helvetica-bold() {
    @include font-face("Helvetica Neue", $weight: bold);

    font-family: "Helvetica Neue", sans-serif;
    font-weight: bold;
    font-style: normal;
    font-stretch: normal;
}
```

Now everytime you want to use a font, you just have to include the given mixin and it will add the font-face declaration once to the stylesheet. This way you never include fonts that you don't use.
