### ISSUE TITLE
node-sass issue for node 6+, is it necessary to upgrade node-sass?

### ISSUE THREAD

**Issue by zslucky** [jtangelder/sass-loader#263]
Please refer to [node-sass issue 1629](https://github.com/sass/node-sass/issues/1629), and comment reply in [node-sass issue 1612](https://github.com/sass/node-sass/issues/1612#issuecomment-228993387).

Is it necessary to upgrade node-sass version to 3.8 to support node 6+?

**Comment by jhnns** [comment]
Sorry, I don't know. The sass-loader repository is definitely not the right place to discuss these things. But guessing from @xzyfer I think you do need to upgrade to 3.8 (which was never a problem in my projects).

**Comment by xzyfer** [comment]
Correct node 6 support was added in node-sass@3.8.0.
