### ISSUE TITLE
sassOptions.data.trim is not a function

### ISSUE THREAD

**Issue by tidus2102** [jtangelder/sass-loader#269]
Hi, I got a problem when build sass files with webpack. Here is my package.json, all packages is newest version: 
![screen shot 2016-08-17 at 12 25 56 am](https://cloud.githubusercontent.com/assets/7001637/17709164/4686949a-6412-11e6-9661-f262071ec5cc.png)

Here is my webpack.config.js:
![screen shot 2016-08-17 at 12 29 17 am](https://cloud.githubusercontent.com/assets/7001637/17709190/62f6834c-6412-11e6-9c9a-a0f8c5c7cb3f.png)

My admin.js only has 1 code line:
![screen shot 2016-08-17 at 12 38 02 am](https://cloud.githubusercontent.com/assets/7001637/17709339/ea83cda6-6412-11e6-8082-c98b2201577b.png)

My admin.scss is NOT empty. When I build with webpack, I always got this error:
![screen shot 2016-08-17 at 12 35 06 am](https://cloud.githubusercontent.com/assets/7001637/17709248/917c3874-6412-11e6-8616-656a012740d0.png)

> Module build failed: TypeError: **sassOptions.data.trim is not a function**
>         at Object.module.exports (/Applications/XAMPP/xamppfiles/htdocs/nsms/node_modules/sass-loader/**index.js:211:26**)

Can you help me on this? Thanks

**Comment by tidus2102** [comment]
![screen shot 2016-08-17 at 12 47 56 am](https://cloud.githubusercontent.com/assets/7001637/17709659/46668cd4-6414-11e6-9fa5-39017ccecc13.png)

This line got problem, I don't know why. I try to install old version, event comment this code, but still got error.

Please help me on this! Thanks

**Comment by tidus2102** [comment]
Hi, I found the problem, because of autoprefixer loader. I fixed it. Sorry for reporting wrong issue.

**Comment by daffunn** [comment]
I have the exact same error, how did you fix it?

**Comment by tidus2102** [comment]
Oh I miss your comment. http://d.pr/i/1aGkH => I used "autoprefixer", but didn't notice that this module was deprecated. I change to use this: https://github.com/postcss/postcss-loader and the issue is solved. Hope this help!

**Comment by daffunn** [comment]
👍
