### ISSUE TITLE
move node-sass to peerDependencies?

### ISSUE THREAD

**Issue by tomchentw** [jtangelder/sass-loader#28]
Hi, as `node-sass` currently have [some issue with pre-build binaries](https://github.com/sass/node-sass/issues/497), I'm wondering that if you have plan to move `node-sass` to `peerDependencies` instead of `dependencies`? 

This will allow client to override custom `node-sass` version without fork the `sass-loader` project. Just specify `"node-sass": "1.0.3"` in their `package.json` and it will load the desired version of `node-sass`.

**Comment by jhnns** [comment]
I think we should move it to the `peerDependencies`. There is a greater benefit for most developers to specify the sass version directly (see recent pull-requests and issues regarding node-sass v2).

Now that `peerDependencies` [will *not* be deprecated](https://github.com/npm/npm/issues/6565#issuecomment-74971689).

**Comment by akiran** [comment]
yes

**Comment by jhnns** [comment]
done()
