### ISSUE TITLE
Getting issue on sass @imports

### ISSUE THREAD

**Issue by himanshuara** [jtangelder/sass-loader#287]
Getting the following error when running sass loader in webpack

Module build failed: SyntaxError: Unexpected token (1:1)

```
> 1 | @import 'base/reset';
```

**Comment by gaterking** [comment]
get the same issue.

**Comment by gaterking** [comment]
I solved this issue，
1. require('../scss/main.scss'); Fail
it use webpack module loaders for file scss
2. require("!style!css!sass!../scss/main.scss"); Success

**Comment by gaterking** [comment]
I don't think my solution is right. I can't work with ExtractTextPlugin well.
The new solution is change the ExtractTextPlugin config.
` {
        test: /\.scss$/,
        loader: extractTextPlugin.extract('style-loader'**, ['css-loader', 'sass-loader']**)
      }` 
and then  we can require as option 1 above.

**Comment by deju** [comment]
@gaterking  I got the error too. But still failed when following your solution.

**Comment by gaterking** [comment]
@deju use the option 1 to check sass-loader work. It will inject the Css to html head.
Maybe u can parse you config.

**Comment by szimek** [comment]
Any ideas how to solve it if I want to keep using ExtractText plugin? I'm using webpack 2.1.0-beta.25 and neither `ExtractTextPlugin.extract(['style-loader', ['css-loader', 'sass-loader'])` nor `ExtractTextPlugin.extract(['style-loader', 'css-loader!sass-loader'])` works for me :/ Is there an older version of sass-loader where it worked correctly?

**Comment by gaterking** [comment]
@szimek try this code. it works for me with "webpack": "^2.1.0-beta.25" and "extract-text-webpack-plugin": "^2.0.0-beta.4".
`      loader: extractTextPlugin.extract({
          fallbackLoader: 'style-loader',
          loader: ['css-loader', 'sass-loader']
        })
`

**Comment by Itagiba** [comment]
I am still having the same problem [here](https://github.com/Itagiba/webpack-test). Using the same code as suggested by @gaterking:

`        loader: ExtractTextPlugin.extract({ fallbackLoader: 'style-loader', loader: ['css-loader', 'sass-loader'] })`

And 

```
plugins: [

    new ExtractTextPlugin({ filename: './public/css/custom.css', disable: false, allChunks: true }),
    //Add Bourbon dependency
      new webpack.LoaderOptionsPlugin({
        options: {
          sassLoader: {
            includePaths: require('bourbon').includePaths,
            outputStyle: 'expanded',
          },
          context: '/src/sass',
        }
      }),

 ]

I import my file in my index.jsx like so:

`import '../src/sass/custom.scss'`

```
And the error persists:

```
nexpected token (2:0)

@import 'bourbon';
```

What is wrong with the processing?

**Comment by jhnns** [comment]
Sorry, this issue is too vague. There are a lot of tests that demonstrate that imports are handled correctly.

**Comment by pedrotainha** [comment]
Hi @Itagiba, i' m getting same issue as you and can' t find the solution. Were you able to find the problem? Thanks

**Comment by evilebottnawi** [comment]
@pedrotainha please provide your webpack config

**Comment by d3viant0ne** [comment]
@pedrotainha - No two issues are actually the same, regardless of similar end results.

Create a new issue outlining your problem & provide a minimally repo where the issue can reliably be reproduced.

**Comment by pedrotainha** [comment]
Sorry for causing noise. In fact my issue is not the same. i created a new one here: https://github.com/webpack-contrib/sass-loader/issues/498
