### ISSUE TITLE
use sass.js to ditch Python dependency?

### ISSUE THREAD

**Issue by tycho01** [jtangelder/sass-loader#297]
Currently `sass-loader` and dependent projects such as `angular-cli` require having Python available due to this library's use of `node-sass`. This could potentially be resolved using versions of libsass transpiled to JS by use of Emscripten such as `sass.js`. Might this perhaps be a consideration?

**Comment by jhnns** [comment]
Afaik python is still a [dependency of Node.js' gyp](https://nodejs.org/en/docs/meta/topics/dependencies/#gyp). Why should we get rid of it?

You could create a PR for that and make some performance tests.

**Comment by tycho01** [comment]
I see, fair enough. Thanks.
