### ISSUE TITLE
[webpack 2] Broken when using `LoaderOptionsPlugin`: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by halt-hammerzeit** [jtangelder/sass-loader#298]
https://github.com/webpack/webpack/issues/2684#issuecomment-228266412

> This behavior is intended. Loaders should not access the webpack options (all passed options should be explicit). The plan (for webpack 3) is to remove the default this.options in the loader context and make loaders more independent from webpack env.
The sass-loader accesses this.options.output.path, which it shouldn't do. cc @jhnns
As workaround you can still pass output.path via the LoaderOptionsPlugin.

**Comment by halt-hammerzeit** [comment]
For the googling ones: my temporary workaround for this issue is

```js


configuration.plugins.push
(
	new webpack.LoaderOptionsPlugin
	({
		test: /\.scss$/,
		debug: true,
		options:
		{
			// A temporary workaround for `scss-loader`
			// https://github.com/jtangelder/sass-loader/issues/298
			output:
			{
				path: configuration.output.path
			},

			postcss:
			[
				autoprefixer({ browsers: 'last 2 version' }),
				css_custom_properties(),
				postcss_calc()
			],

			// A temporary workaround for `css-loader`.
			// Can also supply `query.context` parameter.
			context: configuration.context,

			// output:
			// {
			// 	path: path.join(__dirname, 'dist'),
			// }
		}
	})
)
```

**Comment by daslicht** [comment]
is there somewhere an complete example how to use wepack 2 + sass ? please

**Comment by halt-hammerzeit** [comment]
@daslicht Try this:

```js

configuration.plugins.push
(
    new webpack.LoaderOptionsPlugin
    ({
        test: /\.scss$/,
        debug: true,
        options:
        {
            // A temporary workaround for `scss-loader`
            // https://github.com/jtangelder/sass-loader/issues/298
            output:
            {
                path: configuration.output.path
            }
        }
    }
}
```

**Comment by Luchillo** [comment]
This same issue, but it should work, my current `LoaderOptionsPlugin ` config is:

```ts
new LoaderOptionsPlugin({
        debug: true,
        options: {
          context: helpers.root('src'),
          outupt: {
            path: helpers.root('dist'),
          },
          sassLoader: {
            includePaths: [
              helpers.root('node_modules'),
              helpers.root('src'),
            ],
          },
        },
      }),
```

**Comment by destroyerofbuilds** [comment]
Using the latest version of `sass-loader`, version 5.0.1, I'm encountering the same issue reported by @GusCaplan.

By overriding the `options` object using `webpack.LoaderOptionsPlugin`, I'm wiping out the `context` property that `sass-loader` depends on here - https://github.com/jtangelder/sass-loader/blob/master/lib/loader.js#L60

To work around the issue I've set the context object to `__dirname` or `process.cwd()` depending on how I use Webpack 2.2.

I'm using the `LoaderOptionsPlugin` plugin like so:

```javascript
    new webpack.LoaderOptionsPlugin({
      options: {
        context: process.cwd(),
      },
    }),
```

I eneded

**Comment by jhnns** [comment]
You don't need the `LoaderOptionsPlugin` with sass-loader 5.0.0 anymore. All options can be passed as object with the `options` property (see README).

We still do access the webpack options object to read the `context`. This will not be possible with webpack 3 anymore. But since there isn't a good alternative yet, we still need to do that. This is an ongoing discussion but shouldn't concern you. :)

**Comment by halt-hammerzeit** [comment]
@jhnns Which new option exactly are you talking about?

**Comment by jhnns** [comment]
```js
module.exports = {
    ...
    module: {
        rules: [{
            test: /\.scss$/,
            use: [{
                loader: "style-loader"
            }, {
                loader: "css-loader"
            }, {
                loader: "sass-loader",
                options: { // <--- these options
                    includePaths: ["absolute/path/a", "absolute/path/b"]
                }
            }]
        }]
    }
};
```

**Comment by halt-hammerzeit** [comment]
@jhnns So, what you're telling is that the new `options.includePaths` parameter is equal to the former `LoaderOptionsPlugin.output.path` parameter?

**Comment by jhnns** [comment]
No. `LoaderOptionsPlugin`can be used to mock/replace the **webpack** options that can be accessed inside the loader via `this.options`. With sass-loader, you don't need to do that. This was designed to be compatible with webpack 1 loaders.

Just pass your options where you configure your loader (like in the example above)

**Comment by jhnns** [comment]
`LoaderOptionsPlugin.output.path` is the `output.path` from the webpack options. It has nothing to do with the sass-loader.

**Comment by halt-hammerzeit** [comment]
@jhnns Still not working. The error has changed though:

```
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)

```

**Comment by halt-hammerzeit** [comment]
I'll create a new issue since this one is unable to be reopened
