### ISSUE TITLE
How do I get this to yell at me when there is an error?

### ISSUE THREAD

**Issue by louisnovick** [jtangelder/sass-loader#301]
So far if there is a missing variable or mixin, it says nothing.  What config would be involved getting this to notify me of the error?

**Comment by RickWong** [comment]
@louisnovick Were you able to find a fix for this problem?

**Comment by louisnovick** [comment]
I was mistaken, I get errors in both terminal and in my browser.  I can't remember what I was seeing when I posted this, thanks.
