### ISSUE TITLE
Use custom importer

### ISSUE THREAD

**Issue by jhnns** [jtangelder/sass-loader#31]
Just wanted to point out that custom importers have been implemented with sass/libsass#21. They are currently being tested and it will take some time until node-sass provides an api, so it's still a way to go.

With custom importers we're able to plug-in webpack's resolving algorithm.

**Comment by plasticine** [comment]
https://github.com/Ferocia/johanna/issues/4170

**Comment by haustraliaer** [comment]
Is this now working? Or is there more to do with setting up sass-loader to @import from node_modules etc. Would be keen to test it out (I could just depend on the repo, rather than npm, I guess) if it's ready.

**Comment by jhnns** [comment]
> Is this now working?

Nope, we need to adjust the sass-loader for this. But I guess it's ready to be implemented :grimacing:

**Comment by izaakschroeder** [comment]
@jhnns @haustraliaer see above PR.

**Comment by haustraliaer** [comment]
:tada: Thanks everyone! Works like a dream.
