### ISSUE TITLE
CSS incorrect order

### ISSUE THREAD

**Issue by callumacrae** [jtangelder/sass-loader#318]
Hello!

I have the following section in my main SCSS file:

```scss
// load vendors
$icon-font-path: "~bootstrap-sass/assets/fonts/bootstrap/";
@import "~bootstrap-sass/assets/stylesheets/_bootstrap.scss";
@import "~@samknows/css-framework/dst/samknows.css";
@import "vendor/vuejs";
```

In my output CSS, I'm getting them in the following order:

```
samknows/css-framework
bootstrap
vuejs
```

This is pretty critical: build tools shouldn't be changing the order of CSS!

Any idea how I can fix this?

**Comment by jhnns** [comment]
I'm pretty confident that the sass-loader is not changing the order. We have a lot of tests for that. Please remove every other loader and try to remove as much code as possible while the error still occurs. This will help to track down the problem.

**Comment by callumacrae** [comment]
I was completely wrong about what was causing this: basically, the stuff at the top _wasn't_ samknows/css-framework, it was the CSS from my vue components added by vue-loader.

Oops!

**Comment by jgornick** [comment]
@callumacrae Did you ever solve why the order is not right?

**Comment by callumacrae** [comment]
Yeah it was user error - it was one of my Vue modules being required first and adding bootstrap again. Wasn't a problem in this.
