### ISSUE TITLE
sass-loader@4.0.2 requires a peer of node-sass@^3.4.2 but none was installed.

### ISSUE THREAD

**Issue by brendonco** [jtangelder/sass-loader#320]
I'm getting below after upgrade of node-sass to ^4.0.

sass-loader@4.0.2 requires a peer of node-sass@^3.4.2 but none was installed.

**Comment by shishir-srivastava** [comment]
I'm facing the same issue. 
I was able to get around it by installing version 3.4.2 of node-sass, like so:
`npm install node-sass@3.4.2 --save-dev`

**Comment by jbruni** [comment]
Yep.

I have all current latest in my package,json:

```
    "gulp-sass": "^3.0.0",
    "node-sass": "^4.0.0",
    "sass-loader": "^4.0.2"
```

Using Yarn I got `warning Incorrect peer dependency "node-sass@^3.4.2".`

**Comment by shai32** [comment]
same problem

**Comment by cakeinpanic** [comment]
Moreover it fails on mac if node-sass 4.0.0 is installed in project by itself
and i've got glorious
`Fatal error: undefined is not a function`
from webpack 

please add node-sass as a dependency

**Comment by skyrpex** [comment]
Related PR: https://github.com/jtangelder/sass-loader/pull/319

**Comment by jhnns** [comment]
"Fixed" since node-sass 4 was no valid peer dependency.
