### ISSUE TITLE
nested imports of sass files crash node

### ISSUE THREAD

**Issue by johnkaplantech** [jtangelder/sass-loader#325]
If I import sass files nested more than one deep and try to build with the webpack sass-loader, node crashes. This occurs even if the second imported file is blank.
node(7650,0x106907000) malloc: *** error for object 0x101b11a6c: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

source:
proj/app/sass/_any.scss
```
<blank>
```
proj/app/sass/_theme-default.scss - note here if you comment out the @import 'any' line, the crash goes away. You can also crash it by commenting out the import, but then referencing a variable that doesn't exist - i.e. change 'background: white;' to 'background: $bad;'
```
@import 'any'
.theme-default-header {
    background: white;
    color: black;
}
```
proj/app/sass/main.scss
```
 @import 'theme-default'
```
proj/app/components/Header.jsx
```
    import React from 'react'
    import '../../sass/main.scss'

    export default class Header extends React.Component {
         render() {
            return (
                <div className='theme-default-header'>
                    'This is the header.'
                </div>
            )
        }
    }
```
project config using # react-boilerplate - Boilerplate for "SurviveJS - React"
webpack config part:
```   
    exports.setupScss = function(paths) {
        return {
            module: {
                loaders: [{
                    test: /\.scss$/,
                    loaders: ['style', 'css', 'sass'],
                    include: paths
                }]
            }
        };
    }
```
versions:
{
  "name": "react-boilerplate",
  "private": true,
  "version": "2.5.6",
  "description": "Boilerplate for [SurviveJS - React](http://survivejs.com/react/introduction/)",
  "scripts": {
    "stats": "webpack --profile --json > stats.json",
    "start": "webpack-dev-server",
    "deploy": "gh-pages -d build",
    "build": "webpack",
    "test": "jest",
    "test:lint": "eslint ./app ./tests --ext .js --ext .jsx --ignore-path .gitignore --ignore-pattern dist --cache"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "babel-core": "^6.9.0",
    "babel-eslint": "^6.0.4",
    "babel-jest": "^16.0.0",
    "babel-loader": "^6.2.4",
    "babel-polyfill": "^6.13.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-react-hmre": "^1.1.1",
    "babel-preset-survivejs-kanban": "^0.3.3",
    "bignumber.js": "^2.4.0",
    "bintrees": "^1.0.1",
    "clean-webpack-plugin": "^0.1.9",
    "css-loader": "^0.23.1",
    "eslint": "2.10.2",
    "eslint-loader": "^1.3.0",
    "eslint-plugin-react": "^5.1.1",
    "expose-loader": "^0.7.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "gh-pages": "^0.11.0",
    "html-webpack-plugin": "^2.17.0",
    "html-webpack-template": "^5.0.0",
    "isparta-instrumenter-loader": "^1.0.0",
    "jest": "^16.0.2",
    "karma": "^0.13.22",
    "karma-coverage": "^1.0.0",
    "karma-mocha": "^1.0.1",
    "karma-phantomjs-launcher": "^1.0.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-spec-reporter": "0.0.26",
    "karma-webpack": "^1.7.0",
    "mocha": "^2.5.2",
    "npm-install-webpack-plugin": "4.0.0",
    "phantomjs-polyfill": "0.0.2",
    "phantomjs-prebuilt": "^2.1.7",
    "react-addons-perf": "^15.1.0",
    "react-addons-test-utils": "^15.1.0",
    "react-test-renderer": "^15.3.2",
    "style-loader": "^0.13.1",
    "webpack": "^1.13.1",
    "webpack-dev-server": "^1.14.1",
    "webpack-merge": "^0.13.0",
    "webpack-validator": "^2.1.1"
  },
  "dependencies": {
    "bignumber": "^1.1.0",
    "react": "^15.1.0",
    "react-dom": "^15.1.0",
    "sass": "^0.5.0",
    "sass-loader": "^4.1.0",
    "worker-loader": "^0.7.1"
  },
  "jest": {
    "testRegex": "(/test/.*|\\.(Test))\\.(js|jsx)$",
    "testPathIgnorePatterns": [
      "utils"
    ]
  }
}

**Comment by jhnns** [comment]
Sorry. [There are tests for nested imports](https://github.com/jtangelder/sass-loader/blob/fee3593e5f8658b4afd1f01bc8308718ca0fd439/test/sass/imports.sass) and I use them every day, so I doubt that this is related to the sass-loader.

Please create a minimal example and instructions on how to reproduce the error. I'll reopen it this, if it's a confirmed problem with the sass-loader.

Since this is an error in the C stack, I assume that you're using a custom importer which throws an error.
