### ISSUE TITLE
No stylesheets!

### ISSUE THREAD

**Issue by studioraygun** [jtangelder/sass-loader#327]
No styles being included. when index.scss is updated the page reloads but the page remains complete unstyled.

index.js includes:

`require('./index.scss');`

webpack.config.js looks like:

```
module.exports = {
  module: {
    loaders: [
      {
        test: /\.scss$/,
        loaders: ["style-loader", "css-loader", "sass-loader"]
      }
    ]
  }
}
```

What's going on?

**Comment by jhnns** [comment]
There's no entry point. Please take a look at our unit tests and examples to get a working example.

**Comment by studioraygun** [comment]
Do you have any specific examples? I've already lost half a day to this. Thanks.
