### ISSUE TITLE
webstorm Cannot resolve directory '~bulma'

### ISSUE THREAD

**Issue by bigggge** [jtangelder/sass-loader#332]
I am using vue2

**App.vue**

<img width="317" alt="2016-12-22 4 30 16" src="https://cloud.githubusercontent.com/assets/9855604/21420377/62baa312-c868-11e6-9b12-2ac1c14f1a52.png">

How to solve it?Thanks

**Comment by jhnns** [comment]
Sorry, this is no WebStorm support forum.

Besides that, it works in my WebStorm:
![bildschirmfoto 2016-12-23 um 12 38 37](https://cloud.githubusercontent.com/assets/781746/21453167/cf491dde-c90c-11e6-9fc6-eb59d814f20c.jpg)
