### ISSUE TITLE
fonts not loaded with souceMap

### ISSUE THREAD

**Issue by LeG3nDz** [jtangelder/sass-loader#345]
Hi community,

I've enable the sourceMap with this :

`loaders: ['style', 'css?sourceMap', 'sass?sourceMap']`

And create blob url in my <head> :

`<link rel="stylesheet" href="blob:http://domaine.lan/deaa8955-fe9b-4026-9246-42c34ae6af8d">`

But with blob data, my all @font-face rules aren't loaded. The path is correct :

```
@font-face {
  font-family: 'icomoon';
  src: url("/bundles/icefrontend/assets/fonts/icomoon/icomoon.woff?v=1") format("woff");
  font-weight: normal;
  font-style: normal; }
```

But the font is juste not load in my browser.

Do you have any idea ?

Thank you :)

**Comment by jhnns** [comment]
You don't need to add a blob url. Please reference your fonts relatively and use the file-loader.
