### ISSUE TITLE
Integrating with css-loader with modules turned on

### ISSUE THREAD

**Issue by ujh** [jtangelder/sass-loader#350]
I'm not sure if this is the right place to ask, but I wonder if there's a way to integrate with the css-loader with modules turned on. Given the following SCSS:

``` scss
.el1 {
  // some declarations
  .sub1 {
    //some more
  }
}
```

I can use `styles.el1` and `styles.sub1` as class names in my React component. But as both of them are getting mangled I can't just use `styles.el1` and add a `className="sub1"` to elements inside the component as `sub1` isn't even the class name anymore. Is there a way to make this work or do I have to accept that nesting classes won't work?

BTW, here's the relevant bit of my webpack config:

``` javascript
  module: {
    loaders: [{
      test: /.jsx?$/,
      loader: 'babel-loader',
      exclude: /node_modules/,
      query: {
        presets: ['es2015', 'react', 'stage-2']
      }
    }, {
      test: /\.scss$/,
      loader: combineLoaders([{
        loader: 'style-loader'
      }, {
        loader: 'css-loader',
        query: {
          modules: true,
          localIdentName: '[name]__[local]___[hash:base64:5]',
          sourceMap: true
        }
      }, {
        loader: 'sass-loader',
        query: {
          sourceMap: true
        }
      }])
    }]
  },
```

**Comment by ujh** [comment]
There's this workaround, but it would be great if there were a better way:

``` scss
.el1 {
  :global(.sub1) {
  }
}
```

**Comment by borela** [comment]
It's how [CSS modules work](https://github.com/css-modules/css-modules#exceptions) they are local by default, in your example you could also write as:

```SASS
.el1 {
  // :global is a switch, everything after it becomes global.
  :global .sub1 {
  }
}

.el1 {
  :global {
    .sub1 {
    }
    .sub2 {
    }
  }
}
````

Personally I use different extensions, `.mscss` for files that contain modules and  `.scss` for files without modules, that way I can write global css without enveloping them in the switch `:global` switch.

**Comment by ujh** [comment]
Thanks for your answer @borela! In the end that's what I started to do, use `:global` in a lot of places. I also started splitting up the CSS into smaller files so then this isn't as much of an issue anymore. We'll see with what I'll end up.
