### ISSUE TITLE
Unable to @extend from classes in other files

### ISSUE THREAD

**Issue by manuelro** [jtangelder/sass-loader#355]
I'm having problems trying to get sass-loader to recognize previously computed classes and `@extend` them. For instance, I have two files (file A and B), in file A I create classes dynamically using `@each`, in file B I want to `@extend` from one of the classes dynamically created on file A. I get the following error:

```
ERROR in ./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-22358182!./~/sass-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./app/src/renderer/App.vue
Module build failed:
  @extend .o-color--black;
         ^
      "mark" failed to @extend ".o-color--black".
The selector ".o-color--black" was not found.
Use "@extend .o-color--black !optional" if the extend should be able to fail.
      in D:\Documents\Projects\box\box-desktop-vue\v1\boxscreen-desktop\app\node_modules\composite-css\stylesheets\vendor\_normalize.scss (line 175, column 11)
 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-22358182!./~/sass-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./app/src/renderer/App.vue 4:14-272
 @ ./app/src/renderer/App.vue
 @ ./app/src/renderer/main.js
```

I'm using Vue and Webpack.

On the Vue side, I have something like this:
```
<style lang="scss">
  @import "~some-package/stylesheets/A.scss";
  @import "~some-package/stylesheets/B.scss";
</style>

...
```

Any help would be greatly appreciated.

**Comment by patrickodacre** [comment]
@manuelro Did you solve this problem? I'm having the same issue.

**Comment by manuelro** [comment]
No, but i'll have to. I'm planning to create isolated environments to reproduce the failure and understand what's going on. I'm currently working on another project, but I will eventually get back to this (cause I have too.)

**Comment by dancrumb** [comment]
I think this is a `node-sass` issue. 

I hit this problem, found *this* issue and then tried to diagnose it. I was able to recreate the problem just using `node-sass` (which is the heart of the sass-loader).

I'm continuing to investigate and will link to the relevant issue once I find it

**Comment by dancrumb** [comment]
Check out node-sass/#1469

Looks like this all stems Sass behaviour and is considered working as designed.

**Comment by cyb-prajaktac** [comment]
How did you solve the issue? I upgraded `node-sass` to `4.5.0` but still it is not working.

**Comment by karanpvyas** [comment]
Any update on this? I'm facing the issue too 😞

**Comment by bs-thomas** [comment]
I'm having this issue only when using the "importer" option in "node-sass" and resolving a CSS file and returning { path: file } as per the node-sass README.md documentation.

**Comment by Nitesh300** [comment]
Hi guys i am facing the same problem. Any luck on this issue?
