### ISSUE TITLE
"box-shadow" is parsed wrong

### ISSUE THREAD

**Issue by wzup** [jtangelder/sass-loader#356]
Not sure if this is an issue of `sass-loader` but it looks so.

For some reason `box-shadow` returns value that is considered Invalid by browser. Why does it happen? How to fix?

In my `.scss`:
```
@include box-shadow(0px 1px 5px 1px #c4c3c3);
```

Returns this:
```
-webkit-box-shadow: compact(0px 1px 5px 1px #c4c3c3, false, false, false, false, false, false, false, false, false);
-moz-box-shadow: compact(0px 1px 5px 1px #c4c3c3, false, false, false, false, false, false, false, false, false);
box-shadow: compact(0px 1px 5px 1px #c4c3c3, false, false, false, false, false, false, false, false, false);
```

In a browser dev tools:

![compass - box-shadow - google chrome 2017-01-31 20 19 32](https://cloud.githubusercontent.com/assets/3880497/22465455/c1ebf04a-e7f6-11e6-9b29-98be2b6be901.png)

In a `<script>` tag:

![compass - box-shadow - google chrome 2017-01-31 20 52 02](https://cloud.githubusercontent.com/assets/3880497/22465591/72948ed4-e7f7-11e6-8295-664adf63ffe6.png)

**Comment by jhnns** [comment]
This is definitely not a sass-loader problem.

Why are you using a mixin for the box-shadow anyway? It's supported in all major browsers.
