### ISSUE TITLE
'node-sass' options do not work, are not applied. 'compact' is applied twice

### ISSUE THREAD

**Issue by wzup** [jtangelder/sass-loader#357]
> You can pass options to `node-sass` by defining a `sassLoader `property on your webpack.config.js

Well, that doesn't work. This is my config for `sass-loader` with some option from `node-sass`. The most important option here is `outputStyle: 'expanded'` and it doesn't work.

```
{
    test: /^((?!\.local).)*scss$/i,
    include: [
        path.resolve(__dirname, '..', 'assets/sass'),
    ],
    loaders: [
         'style?singleton&-sourceMap',
         'css?modules&importLoaders=1&-minimize&localIdentName=[local]', 
         'sass' // <==  no query params applied, so there is no reason for options to be are doubled, see below
    ]
},
sassLoader: {
    includePaths: [
        path.resolve(__dirname, "..", "node_modules/compass-mixins/lib"),
        path.resolve(__dirname, "..", "node_modules/bootstrap-sass/assets/stylesheets"),
    ],
    /* (nested | expanded | compact | compressed) */
    outputStyle: 'expanded',
    sourceComments: true,
    indentWidth: 4,
},
```

And this is the output. 1) It is `compact`. 2) `compact` is applied twice.
How can it be, If I set it to be `'expanded`?

![compass sass loader - google chrome 2017-02-01 00 24 54](https://cloud.githubusercontent.com/assets/3880497/22473883/32a9fb56-e815-11e6-8dc1-e7a3dda38546.png)

Q: What is going on? How to solve it?

**Comment by jhnns** [comment]
Again, not a sass-loader issue. Check the transition mixin (you don't need a mixin for that too).
