### ISSUE TITLE
Explicitly depend on node-sass 1.2.2

### ISSUE THREAD

**Issue by appsforartists** [jtangelder/sass-loader#36]
`npm install sass-loader@0.3.1` throws a "module did not self-register" error and fails due to [an issue with node-sass 1.2.3](https://github.com/sass/node-sass/issues/550).  In the mean time, sass-loader should explicitly prefer 1.2.2.

**Comment by gpbl** [comment]
The "module did not self-register" appears also with node 0.12

**Comment by jhnns** [comment]
Damn!

**Comment by gpbl** [comment]
Seems it's going to be fixed soon :) https://github.com/sass/node-sass/issues/627

**Comment by jhnns** [comment]
Starting with 1.0.0, node-sass is now a `peerDependency`
