### ISSUE TITLE
@import *.css makes module not found error: Can't resolve

### ISSUE THREAD

**Issue by morriq** [jtangelder/sass-loader#360]
Hello I'm using sass-loader 4.1.1 with webpack2. My sass's part of webpack config is

```
new webpack.LoaderOptionsPlugin({
        test: /\.(css|scss)$/,
        options: {
          sassLoader: {
            includePaths: [path.resolve(projectRoot, 'node_modules'), path.resolve(appSrc, '..')]
          }
        }
      })
```

and it works for scss @imports:

```
@import 'node_modules/bootstrap/scss/bootstrap-flex';

@import 'node_modules/animatewithsass/animate.scss';
**@import 'node_modules/animate.css/animate.css';**
```
But for animate.css shows error..

> ERROR in ./~/css-loader?sourcemap&minimize!./~/sass-loader?sourcemap!./submodules/NG2Components/src/styles.scss
>     Module not found: Error: Can't resolve './node_modules/animate.css/animate.css' in 'C:\htdocs\NG2\GP.Hub\submodules\NG2Components\src'
>      @ ./~/css-loader?sourcemap&minimize!./~/sass-loader?sourcemap!./submodules/NG2Components/src/styles.scss 3:10-124

Path is real and it should work: https://content.screencast.com/users/morriq/folders/Jing/media/138f913a-eb94-4172-8d37-4aac4a1d09d2/2017-02-02_1546.png

**Comment by leongaban** [comment]
Hi, how did you get your config to recognize the @imports for .scss files? My config is still having problems there. Would you mind a quick look at my setup? http://stackoverflow.com/questions/42058357/webpack-not-understanding-import-statement-in-my-sass-files

**Comment by jhnns** [comment]
I've added a test case for `animate.css`. It works fine.

Just remove the `includePaths` option and use the tilde path to import stuff from `node_modules`, like this:

```
@import '~bootstrap/scss/bootstrap-flex';

@import '~animatewithsass/animate.scss';
@import '~animate.css/animate.css';
```

**Comment by morriq** [comment]
@leongaban seems like someone else resolve your problem. :)

@jhnns thank you but with tilde (~) the imported file is not in webpack's chunk. It's separated and that way, there is requirement to keep node_modules/animate.css/animate.css in build package.

**Comment by jhnns** [comment]
> but with tilde (~) the imported file is not in webpack's chunk

It's just another way of referencing it. The CSS will definitely be in webpack's chunk (whatever that is).

**Comment by wasif12** [comment]
vdfggfdsgdfgs
