### ISSUE TITLE
SyntaxError: Invalid or unexpected token @import in SASS Files

### ISSUE THREAD

**Issue by leongaban** [jtangelder/sass-loader#364]
http://stackoverflow.com/questions/42058357/webpack-not-understanding-import-statement-in-my-sass-files

I found this same issue here: https://github.com/jtangelder/sass-loader/issues/344, however his solution did not fix my problem :(

<img width="689" alt="screen shot 2017-02-05 at 5 25 31 pm" src="https://cloud.githubusercontent.com/assets/191636/22630906/1df957c2-ebc8-11e6-9ad4-a0ee9036c40c.png">

My config:

```      
var path = require('path');
var sass = require("./sass/lifeleveler.scss");

module.exports = {
	entry: './dist/main.js',
	output: {
		filename: 'lifeleveler.app.js',
		path: path.resolve(__dirname, 'dist')
	},
	module: {
		loaders: [
			{
		            test: /\.scss$/,
        		    include: [
        		        path.resolve(__dirname, 'node_modules'),
		                path.resolve(__dirname, './sass')
		            ],
        		    loaders: ["style-loader", "css-loader", "sass-loader"]
			}
		],
		rules: [
			{
				test: /\.tsx?$/,
				loader: 'ts-loader',
				exclude: /node_modules/,
			},
			{
				enforce: 'pre',
				test: /\.tsx?$/,
				use: "source-map-loader"
			}
		]
	},
	sassLoader: {
    	includePaths: [path.resolve(__dirname, "./sass")]
 	},
	resolve: {
		modulesDirectories: ['./sass', 'node_modules'],
		extensions: [".tsx", ".ts", ".js", ".scss"]
	},
	devtool: 'inline-source-map',
	watch: true,
	watchOptions: {
		aggregateTimeout: 300,
		poll: 1000,
		ignored: /node_modules/
	}
};
```

Note when I tried this at the top of my config:

    var css = require("!raw-loader!sass-loader!./sass/lifeleveler.scss");
    var css = require("!css-loader!sass-loader!./sass/lifeleveler.scss");

Got this error: 
> Error: Cannot find module '!raw-loader!sass-loader!./sass/lifeleveler.scss'

Which is why I went with just this: `var sass = require("./sass/lifeleveler.scss");`

**Comment by jhnns** [comment]
The `webpack.config.js` cannot use webpack features. It is executed in node and can only contain node compatible code.

**Comment by leongaban** [comment]
Uhm more explanation please? I've used code directly from the docs and other examples...

**Comment by jhnns** [comment]
You're importing a SCSS file in your webpack.config:

```js
var sass = require("./sass/lifeleveler.scss");
```

Node cannot import SCSS files. It does not support loaders.

**Comment by leongaban** [comment]
Thanks, I removed that file... no errors, but nothing happens when I save my `.scss` file now. I guess I'll have to post another issue. This plugin is suppose to make Webpack 2 compile SASS, I'm using the exact code from the docs...

**Comment by jhnns** [comment]
Which docs? Which plugin?

**Comment by leongaban** [comment]
This plugin! :) All I got webpack2 to compile and build my final JS file, however my styles are all written in .Scss Sass modules. I need to compile those with webpack. Starting to think maybe npm scripts is the way to go.

**Comment by jhnns** [comment]
This is a loader. Loaders are different than webpack plugins.

> I'm using the exact code from the docs...

There is no part in the docs where a sass file is included into the webpack config. Why would you want to do that anyway? ^^

**Comment by leongaban** [comment]
Yeah that was my bad, sorry... I didn't realize this is how Webpack worked, finally got the bug fixed: http://stackoverflow.com/questions/42058357/webpack2-not-understanding-import-statement-in-my-sass-files-how-to-compile-sa/42102403#42102403

Now I see that my styles are actually combined in the final JS app file now, interesting.
