### ISSUE TITLE
Passing the [hash] to css

### ISSUE THREAD

**Issue by acostaf** [jtangelder/sass-loader#371]
Hi People

I've got a sprite that is loading an image that needs to cache busted so I've got static_path and hash that needed to be replaced on e.g. url("#{$static_path}img/menu_spritesheet.png?#{$hash}"), 
and my config is   sassLoader: {  data: jsonToSassVars({static_path: static_path,hash: '[hash]'}) but webpack does not like that 

Any idea or suggestions.

**Comment by jhnns** [comment]
Are you using the css-loader and the file-loader? In that case, you don't need to configure anything. The file-loader will hash all files automatically.

**Comment by acostaf** [comment]
I am using css-loader since the css already contains the file name.

**Comment by jhnns** [comment]
If you're using the css-loader, have you enabled the `url` option (default is enabled, but maybe you've disabled it)?

**Comment by acostaf** [comment]
Do you have a quick sample on that ?

**Comment by jhnns** [comment]
https://github.com/webpack/webpack/tree/master/examples/css-bundle

**Comment by acostaf** [comment]
Sorry jhnns but that sample does not show the url.

**Comment by jhnns** [comment]
Clone the repo, build the example running `build.js` and checkout the result in the `js` directory.

The final url will look like [this](https://github.com/webpack/webpack/tree/master/examples/css-bundle#jsstylecss). The referenced image will be copied to the output folder.
