### ISSUE TITLE
Installation issue: peerDependencies requirements

### ISSUE THREAD

**Issue by lizshannon** [jtangelder/sass-loader#378]
Has someone had this issue before? 

```npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sass-loader" "style-loader" "css-loader" "node-sass" "webpack" "--save"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer babel-loader@6.2.10 wants webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc
npm ERR! peerinvalid Peer sass-loader@6.0.0 wants webpack@^2.0.0

npm ERR! Please include the following file with any support request:
npm ERR!     ...project/npm-debug.log
```
I used this command to install:
`npm install sass-loader style-loader css-loader node-sass --save`

**Comment by jhnns** [comment]
You're using webpack 1 and are trying to install the latest sass-loader. We [removed Webpack 1 support with sass-loader `5.0.0`](https://github.com/jtangelder/sass-loader/blob/master/CHANGELOG.md). You need to run `npm i sass-loader@4`.

Please also read about [peer dependencies](https://nodejs.org/en/blog/npm/peer-dependencies/). The error is quite clear if you know the concept of peer dependencies.
