### ISSUE TITLE
How do I import bootstrap-sass?

### ISSUE THREAD

**Issue by kurtharriger** [jtangelder/sass-loader#40]
added this stuff to webpack loaders:

        {test: /\.scss/, loader: 'style!css!sass?includePaths[]=' +
            (path.resolve(__dirname, "./node_modules"))},
        {test: /\.woff(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "url-loader?limit=10000&minetype=application/font-woff" },
        {test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "file-loader" }

and in my scss:
@import "bootstrap-sass/assets/stylesheets/_bootstrap.scss";

But I get bunch of errors resolving the relative paths with bootstrap-sass

ERROR in ./~/css-loader!./~/sass-loader?includePaths[]=/Users/kharriger/code/webpack-template/node_modules!./src/sass/all.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/bootstrap/glyphicons-halflings-regular.eot in /Users/kharriger/code/webpack-template/src/sass
 @ ./~/css-loader!./~/sass-loader?includePaths[]=/Users/kharriger/code/webpack-template/node_modules!./src/sass/all.scss 2:3068-3130 2:3144-3206

ERROR in ./~/css-loader!./~/sass-loader?includePaths[]=/Users/kharriger/code/webpack-template/node_modules!./src/sass/all.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/bootstrap/glyphicons-halflings-regular.woff in /Users/kharriger/code/webpack-template/src/sass
 @ ./~/css-loader!./~/sass-loader?i

**Comment by jhnns** [comment]
I don't know what the correct settings are, but you probably need to adjust the `$icon-font-path`-variable. Bootstrap provides the possibility to [configure the path to the icon fonts](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_glyphicons.scss). Make sure that the url() is pointing from the imported file (probably `/assets/stylesheets/_bootstrap.scss` in your case) to the font-files.

**Comment by kurtharriger** [comment]
As far as I can tell the relative path to the font files from _bootstrap.scss is correct. I didn't know the icon path could be specified before import, so Ill give that a try.  I was thinking that sass-loader would/should resolve the relative urls and it would just work?

I don't intend to customize bootstrap at the moment so if I still have issues I'll just copy the precompiled in for now. I just figured using the sass-loader would simplify packaging.

Thanks

**Comment by jhnns** [comment]
You need to think from the css-loader's perspective. It gets a css-file with url() statements referencing files. Now you need to start from the css-file's location and walk the relative url to the file and look if the path is correct.

**Comment by kurtharriger** [comment]
Ah okay now I get it.  Perhaps the sass loader to update the resulting css, but not entirely sure how easy that would be. Probably need to use the source map to determine original path or maybe it would be easier to update path prior to processing so output is correct? 

Now I understand why the relative path doesn't just work. Thanks

**Comment by jhnns** [comment]
Related discussions: sass/sass#1015 sass/libsass#532

You could also try [this sass mixin](https://github.com/glebm/sass-rewrite-url) to achieve relative urls.

**Comment by kurtharriger** [comment]
Setting icon path works, but you need to prefix the path with a ~:

$icon-font-path: "~bootstrap-sass/assets/fonts/bootstrap/";
@import "bootstrap-sass/assets/stylesheets/_bootstrap.scss";

If you don't add the ~ then it gets translated to ./bootstrap-sass/assets/fonts/bootstrap.  
Thanks!

**Comment by aguestuser** [comment]
hi all. i got the same error as @kurtharriger then tried the solution he presents, BUT... i then get the following error:

```shell
Module not found: Error: Cannot resolve module 'url' in ...
```

anyone have any guesses as to what's going on or possible fixes?

**Comment by aguestuser** [comment]
answered my own question (which i'll leave here in case anyone else encounters the same problem:

```shell
$ npm install file-loader --save
$ npm install url-loader --save
```

**Comment by jhnns** [comment]
:+1:

**Comment by osasseville** [comment]
Thanks a lot!

**Comment by sahil87** [comment]
:+1:

**Comment by danpantry** [comment]
I found that setting `$bootstrap-sass-asset-helper: true` instead of using `$icon-font-path` solved the issue; `$icon-font-path` was not really helping.

**Comment by jhnns** [comment]
`$bootstrap-sass-asset-helper` might also work. However, setting `$icon-font-path` relative to the *scss* entry file does also work. I'm using this setting in my projects.

**Comment by ale-batt** [comment]
Thanks to @danpantry, `$bootstrap-sass-asset-helper` solve the problem, set the `$icon-font-path` wasn't working

**Comment by jhnns** [comment]
[There is a test for bootstrap](https://github.com/jtangelder/sass-loader/blob/c5f311f2614723129d1d1acbda8d7b136c3badda/test/bootstrapSass/webpack.config.js). It must be related to your local config.

**Comment by crdil** [comment]
I also had this problem. The only thing that worked for me is the following:
```
$bootstrap-sass-asset-helper: true;
@import "../../node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss";
```

**Comment by akras14** [comment]
@danpantry answer is the best ` $bootstrap-sass-asset-helper` option, if anybody else stumbles here.

**Comment by theoxuan** [comment]
@danpantry  Thanks man. You are a life-saver.

**Comment by 6zz** [comment]
@danpantry thank you!  I searched high and low.  only if this was in the README the search would not have been needed.  Can update the README?
```
$bootstrap-sass-asset-helper: true;
@import "~bootstrap-sass/assets/stylesheets/bootstrap";
```

**Comment by jhnns** [comment]
There's a note about this problem at https://github.com/jtangelder/sass-loader#problems-with-url. Why was this not helpful? We have a test for bootstrap: https://github.com/jtangelder/sass-loader/blob/master/test/scss/bootstrap-sass.scss

**Comment by danpantry** [comment]
The note on that problem specifically mentions `$icon-font-path`, which in this case is a red herring (I specifically noted that that *did not work* in my original comment).

**Comment by abobwhite** [comment]
@danpantry @jhnns I too cannot get this to work even with the below:

```
$bootstrap-sass-asset-helper: true;
$icon-font-path: '~bootstrap-sass/assets/fonts/bootstrap/';
@import '~bootstrap-sass/assets/stylesheets/bootstrap';
```

The bootstrap files are loaded fine but is trying to find the font files relative to the file those lines are included from.....

**Comment by satyaprakash-k** [comment]
Thanks @danpantry . Saved my time :+1:

**Comment by Grievoushead** [comment]
This worked for me:
```
@import "~bootstrap-sass/assets/stylesheets/_bootstrap-sprockets.scss";
@import "~bootstrap-sass/assets/stylesheets/_bootstrap.scss";
```

**Comment by nickescobedo** [comment]
Have tried all of the above and more but still receive the following error after trying to import the main bootstrap.scss file.
`ERROR in ./~/css-loader?sourceMap!./src/assets/scss/main.scss
Module not found: Error: Can't resolve 'bootstrap-sass/assets/stylesheets/bootstrap' in '/project/src/assets/scss'
 @ ./~/css-loader?sourceMap!./src/assets/scss/main.scss 3:10-120
 @ ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-3db32f4e!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue
 @ ./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-3db32f4e!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js
 @ multi main`

main.scss
There are no complaints about the fonts files only the main bootstrap file
`$icon-font-path: "~bootstrap-sass/assets/fonts/bootstrap/";
@import "~bootstrap-sass/assets/stylesheets/bootstrap";`

webpack.config.js
Same as: https://github.com/vuejs-templates/webpack-simple/blob/8859f53b51ddeed7739108f220cba33711669d9f/template/webpack.config.js

**Comment by arvinsim** [comment]
Thanks @Grievoushead. Your solution worked for me.

**Comment by tsuz** [comment]
I had a `$icon-font-path: '../old/path !default' in code which prevented from assigning any other values to `$icon-font-path`..

**Comment by moiguitarrock** [comment]
exists a variable that fix the problem with the relative/absolute path, all that you need is set the variable `$bootstrap-sass-asset-helper` in `true` and that's all.

PS: do that before the importation of bootstrap: 

```
$bootstrap-sass-asset-helper: true;
@import "~bootstrap-sass/assets/stylesheets/bootstrap";
```

**Comment by teknicalissue** [comment]
but why doesn't @import "bootstrap" work? 

Would love an explanation for why we need the work around!

**Comment by JohnGallego** [comment]
@moiguitarrock, looking at the network requests, it looks like this setting sets url to an outside server hosting the files instead of the local ones bundled in with webpack.

**Comment by monarchjhaveri** [comment]
@JohnGallego  I don't see this behaviour on my local

**Comment by ChristianGalvez23** [comment]
I need to know the same answer as @teknicalissue wants to know.

**Comment by lorencole** [comment]
> but why doesn't @import "bootstrap" work?

And also why isn't `$bootstrap-sass-asset-helper: true;` the default?
