### ISSUE TITLE
Update for io.js support for node-sass

### ISSUE THREAD

**Issue by realchaseadams** [jtangelder/sass-loader#42]
for io.js users node-sass is failing install with `Error: Module did not self-register.` It looks like node-sass this has been patched for the 2.0 release (https://github.com/sass/node-sass/pull/630).

**Comment by daniel-norman-sociomantic** [comment]
Same error here.

**Comment by jhnns** [comment]
#41

**Comment by jhnns** [comment]
Has been published as `0.4.0`.
