### ISSUE TITLE
Dependency graph and duplicated dependencies on build

### ISSUE THREAD

**Issue by pirelenito** [jtangelder/sass-loader#45]
I am trying to understand how I should require a sass dependency that is a requirement to more than one of my other modules. Something like `normalize.scss` (I am using the scss fork just for convenience). Which in theory should be a dependency of everything (since it should be loaded first).

Suppose I have two modules, maybe:

`play-button.scss`, which would have a dependency to `normalize`:

```sass
@import 'node_modules/normalize.scss';

.play-button {
  // its style
}
```
and another module: `restart-game-screen.scss`,  which would also have a dependency to `normalize`:

```sass
@import 'node_modules/normalize.scss';

.restart-game-screen {
  // its style
}
```

Shouldn't the loader identify that the `normalize.scss` is used in two places and only bundle it once? It looks like this might not be supported right now by the way `libsass` works. If it doesn't, what is the best approach to handle these shared common modules?

Just to be clear, I usually organize my application`s component (Backbone or React) like:
* `player-button.scss`
* `player-button.js`

Each component has its own dependency graph. Meaning that at the JS file I have a requirement to the SCSS file.

An old solution to this problem is to have a 'manifest file': a single entry point for the entire application stylesheet that requires (`@import`) everything.

**Comment by akiran** [comment]
I recommend you use a file  _common.scss (or similar name)  and all common styles and imports in it.

Import this common.scss in other scss files.
This will also make you scss more manageable. You can edit in one file instead of all the files.

**Comment by andycmaj** [comment]
@pirelenito look into https://github.com/wilsonpage/sass-import-once and http://4waisenkinder.de/blog/2014/03/06/import-once-in-sass-the-foundation-way/

the duplicated imports is a problem with sass itself: https://github.com/sass/sass/issues/156

**Comment by pirelenito** [comment]
Hi @andycmaj, thanks for pointing me to the sass issue and the alternate solutions.

But I guess, for the moment, I'll keep just an `index.scss` with all the `@imports` for my project.

**Comment by jhnns** [comment]
LESS is handling these issues [way more elegantly](https://github.com/webpack/less-loader/issues/7#issuecomment-69595045)...
