### ISSUE TITLE
Can't get hot module replacement to work with sass-loader version newer than 0.2.0

### ISSUE THREAD

**Issue by justin808** [jtangelder/sass-loader#47]
I'm trying to update my rails-webpack-reactjs tutorial project to the latest dependencies.

https://github.com/justin808/react-webpack-rails-tutorial/tree/update-to-latest

The only dependency that does not work is sass-loader. Any version greater than 0.2.0 gives the following error:

```
ERROR in ../~/css-loader!../~/sass-loader?outputStyle=expanded&imagePath=/assets/images&includePaths[]=/Users/justin/j/react/react-webpack-rails-tutorial/webpack/assets/stylesheets!./assets/stylesheets/test-sass-stylesheet.scss
TypeError: Object function (from) {
			return !!~this.indexOf(from);
		} has no method 'replace'
```

Thus, I'm stuck at 0.2.0. Any ideas on what I can do further pinpoint what change broke my app?

Has anybody else gotten the hot-reload server to work with a version greater than 0.2.0?

Thanks.

**Comment by jhnns** [comment]
Mhmm I'm not quite sure ... could be an issue with [sass-graph](https://github.com/xzyfer/sass-graph). Could you remove the [calls of `markDependencies()`](https://github.com/jtangelder/sass-loader/blob/master/index.js#L42) in your local installation of the sass-loader and check, if the problem still exists?

**Comment by justin808** [comment]
That does solve the error. What do you recommend next?

**Comment by justin808** [comment]
@jhnns I'm debugging your latest with the latest from sass-graph (1.0.1). Any reason you're locked in at an older version of sass-graph?

**Comment by justin808** [comment]
@jhnns I've tracked down the problem to sass-graph using for(var a in someArray) syntax and one of my dependencies must have added a method to array. Thus, crash, just as explained here: http://stackoverflow.com/a/3010848/1009332

https://github.com/xzyfer/sass-graph/blob/master/sass-graph.js#L54

```javascript
  for (var i in imports) {
    [this.dir, cwd].forEach(function (path) {
      if (path && this.loadPaths.indexOf(path) === -1) {
        this.loadPaths.push(path);
      }
    }.bind(this));
    var resolved = resolveSassPath(imports[i], _.uniq(this.loadPaths));
    if (!resolved) return false;

    // recurse into dependencies if not already enumerated
    if(!_.contains(entry.imports, resolved)) {
      entry.imports.push(resolved);
      this.addFile(fs.realpathSync(resolved), filepath);
    }
  }
```

**Comment by akiran** [comment]
@justin808, 
We submitted a pull request to sass-graph to fix some of the issues with sass-loader.
Since npm release was not made at that time, we tagged it to git commit.

Now @xzyfer is maintaining sass-graph and an npm release was made recently.
We should test it with sass-loader and migrate to latest version of sass-graph.

**Comment by justin808** [comment]
@akiran is there a fork/branch I should pull? I'm going to check that just changing the array iteration fixes my issue.

**Comment by akiran** [comment]
Now sass-graph is maintained at
https://github.com/xzyfer/sass-graph

**Comment by xzyfer** [comment]
Hey all, feel free to open issues and PR in sass-graph. I'm _actively_ maintaining it.

There's a lot a clean up work to be done, which is coming.

**Comment by justin808** [comment]
https://github.com/xzyfer/sass-graph/pull/7

**Comment by xzyfer** [comment]
I've had a preliminary look at xzyfer/sass-graph#7. I have some feels about it.

One way or another expect a new npm release with this issue patched within 24hrs.

**Comment by xzyfer** [comment]
I've published sass-graph@1.0.3 that should address the issue raised by @justin808 .

**Comment by justin808** [comment]
I posted a fix to sass-loader to reference my own fork of sass-graph.

However, sass-graph just fixed my reported issue.

![commits_ _xzyfer_sass-graph](https://cloud.githubusercontent.com/assets/1118459/5996870/2374f5fe-aa56-11e4-8f1f-9dbba8181dcb.jpg)

Please comment in this issue when this version sass-loader is updated to this version of sass-graph.

**Comment by akiran** [comment]
Did latest version of sass-graph fixed your issues ?

Then we can update sass-loader and make an npm release.

**Comment by xzyfer** [comment]
I've just published a sass-graph@1.0.3 which passes the test case added by @justin808 .

**Comment by justin808** [comment]
@akiran Can we update sass-loader? I just submitted a PR, albeit a very simple one, to update the version dependency.

**Comment by jhnns** [comment]
Fixed?

**Comment by jhnns** [comment]
We don't depend on sass-graph anymore.
