### ISSUE TITLE
Pass variables to scss files

### ISSUE THREAD

**Issue by nwhite89** [jtangelder/sass-loader#49]
I'm wanting to pass variables from webpack to the scss files, for example opacity is able to be changed by a user and stored in the db. Ideally I'd pass the variable same way as you do to JS files via webpack and pass them straight through to the SCSS files before compilation.

**Comment by jhnns** [comment]
Could you show an example how you'd expect things to work?

I'm afraid that this is currently not possible (if I got it right). But with custom importers #31 it's probably possible. Then you can write a special loader, which generates scss code to import your dynamic vars.

**Comment by nwhite89** [comment]
@jhnns thank you for your response I'm thinking of the ``webpack.DefinePlugin`` so perhaps something like


```js
webpack.DefinePlugin({
  'SCSS_OPACITY': '0.4'
});
```
```scss
$opacity: SCSS_OPACITY;
@include opacity($opacity);
```

but perhaps if it's easier for it to create a file with all of them and somehow matching ``SCSS_OPACITY`` to be ``$SCSS_OPACITY`` ?? and attaching the variables above of files when generating? what are your thoughts?

**Comment by jhnns** [comment]
Mhmmm your solution would probably work too.

And when you need to access the variables also via client-side JavaScript:

```javascript
webpack.DefinePlugin(require("./styles/variables.js"));
```

**Comment by nwhite89** [comment]
Yeah, using the ``definePlugin`` I think would be ideal because it would use the current inner workings of webpack but also allow for variables to be used across both the JS and SCSS files which I'm not entirely sure when you may need it but it would be more powerful I feel.

**Comment by jhnns** [comment]
Oh, there are use-cases where this is required... :)

I'll check that!

**Comment by nwhite89** [comment]
Using this perhaps? https://github.com/webpack/docs/wiki/list-of-plugins#dependency-injection

Without looking into it I would hazard a guess it should make it easier? (hopefully) :)

**Comment by Kasu** [comment]
Hi! I've tackled the same problem on my own, the solution looks like this:

```javascript
var sass = encodeURIComponent(jsonToSassVars(sassGlobals));
var webpackConfig = {
    module: {
        loaders:[
            {test: /.scss$/, loader: "style!css!sass!prepend?data=" + sass}
        ]
    },
}
```

**Comment by nwhite89** [comment]
@kasu any chance of them being made Open Source?

**Comment by Kasu** [comment]
@nwhite89 Sure thing, here you go: The [prepend-loader](https://gist.github.com/Kasu/29452051023ff5337bd7) and [jsonToSassVars](https://gist.github.com/Kasu/ea4f4861a81e626ea308).

**Comment by nwhite89** [comment]
@Kasu cheers :+1:

**Comment by jhnns** [comment]
@Kasu haha, nice!
@nwhite89 no I don't think so. I don't want to extend the language itself...

**Comment by EdwardIrby** [comment]
@Kasu really liked your work so I went and forked it into a npm loader https://www.npmjs.com/package/jsontosass-loader

**Comment by nwhite89** [comment]
@EdwardIrby :+1:

**Comment by Kasu** [comment]
@EdwardIrby cool :)!

**Comment by jhnns** [comment]
Is @EdwardIrby 's solution working for you? I'd like to link the loader in our README, but I'm not sure about how safe that string replaces are :grin: ...

Do you have any experience on this?

**Comment by wendellm** [comment]
@EdwardIrby I don't think you should return a json file but a js file that returns an json object. This way you can do custom calculations to darken or lighten a color for example or other caculations you might need.

**Comment by nightgrey** [comment]
@nwhite89 @EdwardIrby @jhnns I think this could be what you guys need: [Sassport](https://github.com/davidkpiano/sassport)

I just found this myself and didn't use it yet, but it seems like it enables you to do what you want - sharing values between JavaScript and Sass.

**Comment by jhnns** [comment]
Thx @nightgrey 

This issue can now also be solved with the `data`-option. Just [define any Sass code](https://github.com/jtangelder/sass-loader#environment-variables) which will be prepended to the actual entry file.

**Comment by matt-newell** [comment]
@jhnns can we see a working example of the data option? Having issues getting it to work

**Comment by jhnns** [comment]
> It's a bit confusing where to options, query params or sassLoader

I know... this will be simpler with webpack 2 where there is a dedicated way to set the options (query params didn't work so well with more complex use-cases).

**Comment by mjw56** [comment]
@jhnns I can get the environment variable to be passed in via `data`-option and I see that it is working in the app.

I am doing something like:

```js
sassLoader: {
  data: '$myColor: green;',
},
```

and then in a random .scss file I just use `color: $myColor`. It works, I can see the color appearing in the application, but I am also seeing errors at compile time: ```Undefined variable: "$myColor"```. Is there a step that I am missing here to complete this so as to not get those errors?

**Comment by jhnns** [comment]
Nope, looks good. There must be a different error in your setup.

**Comment by mjw56** [comment]
@jhnns Yeah, the issue was that I wasn't including this option on the server bundle as well. It is working, thanks!

**Comment by pnkapadia6** [comment]
Is there a way to pass variables to scss file from a js file, where it is imported?

**Comment by epegzz** [comment]
Hey guys, had the same needs for passing vars to my sass files, so i also created a little webpack loader based on @Kasu's gist. It lets you import vars directly via webpack, or by specifying a JSON or JS file. [Check it out](https://www.npmjs.com/package/@epegzz/sass-vars-loader) :)

**Comment by Cleod9** [comment]
After much digging around, I found an even easier solution:

https://www.npmjs.com/package/webpack-append

Despite its misleading name, this package does, in fact, prepend specified text to the beginning of each file. And unlike `prepend-loader`, it doesn't have any issues with `style-loader` 😄

**Comment by epegzz** [comment]
How is that easier than passing the vars directly in webpack config or by specifying paths to JS/JSON files?
https://github.com/epegzz/sass-vars-loader does support exactly that:

```js
// webpack.js
sassVars: {
  vars: {
    someColor: red,
    someOtherColor: blue,
   }
 }
```

…and you're ready to use them anywhere in your scss
```scss
.foo {
  color: $someColor;
}
```

**Comment by Cleod9** [comment]
@epegzz This way you can basically just write Sass rather than JS. Also by prepending as a string you could theoretically just use `fs` to prepend a full .scss file if you wanted. To give you some context, the earlier answer of `prepend-loader` sufficed for me for a time, but broke after I had switched from `ExtractTextPlugin` to `style-loader`

**Comment by epegzz** [comment]
@Cleod9 writing JS or JSON inside the webpack config which is JS itself feels way nicer to me. And the OP wanted to pass data potentially stored in a database. Chances are, those data already come as JSON or even JS object when he's loading them inside the webpack.js. But in the end, it's all a matter of personal preference and specific use case :)

**Comment by Cleod9** [comment]
@epegzz True, and I appreciate your plugin btw! I think for others who land in this thread will find that at least one of these solutions will work for them (this thread is like the number one search result for "sass variables through webpack" 😉  )

**Comment by IAMtheIAM** [comment]
@epegzz is it webpack2 compatible? Webpack2 doesn't allow custom properties on the webpack config, must use the `LoaderOptionsPlugin` for any custom properties.

**Comment by epegzz** [comment]
@IAMtheIAM haven't tested yet, but no, probably not then, thx for pointing it out! :) 

The following should work with webpack2 though, rigth?

```js
// webpack.js
var sassVarsConfig = querystring.stringify({
    files: [
        path.resolve(__dirname, '..', 'src/shared/styles/vars/_breakpoints.js'),
    ]
});

return {
    loader: ExtractTextPlugin.extract(
        'style',
        'css!sass!@epegzz/sass-vars-loader?' + sassVarsConfig
    ),
  //...
```

**Comment by IAMtheIAM** [comment]
@epegzz Good job dude! that worked perfectly, thanks, I was struggling for hours to get any of these options to work with webpack 2, so that I can take a JS/JSON file and append it before all scss files. Great!

**Comment by IAMtheIAM** [comment]
@epegzz  I made a pull request fixing your loader, to allow users to pass "vars" directly on the webpack config, rather than in an external file. So now both options work. Please review and approve it so others can use :-)

You just have to JSON.stringify anything in the vars property like this:

```
const sassVarsConfig = querystring.stringify({
   files: [
      path.resolve(helpers.paths.appRoot + '/styles/sass-js-variables.js')
      // path.resolve(__dirname, '/path/to/breakpoints.js'), // JS
      // path.resolve(__dirname, '/path/to/colors.json'), // JSON
   ],
   vars: [JSON.stringify({'susyDebug': $susyDebug})],
});
```
Then, your loader should look something like:
```
loaders: ['css?sourceMap', 'postcss', 'sass?sourceMap', '@epegzz/sass-vars-loader?' + sassVarsConfig],
```

**Comment by epegzz** [comment]
awesome @IAMtheIAM, merged and pushed to npm :)

**Comment by 534N** [comment]
@epegzz I can't install your module: 
```
npm ERR! Invalid name: "@epegzz/sass-vars-loader"
```

**Comment by epegzz** [comment]
@534N I answered in epegzz/sass-vars-loader#6 :)

**Comment by nagarajay** [comment]
@jhnns Is the data option working correctly for Webpack V2. @epegzz @IAMtheIAM  great solution. I will try to use it as stated.

**Comment by jhnns** [comment]
@nagarajay Does [this](https://github.com/webpack/webpack/issues/2684#issuecomment-255155479) work for you?

**Comment by mkarajohn** [comment]
I understand that the solutions above allow us to define and use SASS variablesin our `sass` files without actually touching them, but how about **overriding** existing variables? 

For example, could we override the `$enable-flex` variable of Bootstrap 4 from `false` to `true` in order to [build the flexbox version of the grid](http://v4-alpha.getbootstrap.com/getting-started/flexbox/#how-it-works) ?

**Comment by jhnns** [comment]
When they're using [`!default`](https://robots.thoughtbot.com/sass-default), yes. Otherwise, no.

**Comment by CallMeXYZ** [comment]
With using ` "sass-loader": "4.0.2","webpack": "^1.13.2",`, it comes to me that the environment variable function doesn't work.

**Comment by JasonEtco** [comment]
I think it's worth nothing that @jhnns above solution is great, but the description on how to actually use it wasn't clear. The `sassLoader` object has to be in the root of your webpack's exported object, like this:

```js
module.exports = {
  entry: [...],
  module: {
    loaders: [...],
  },
  sassLoader: {
    data: '@import "variables";',
    includePaths: [
      path.resolve(__dirname, '../src/scss/tools'),
    ],
  },
};
```

**Comment by jhnns** [comment]
While this is true for webpack 1, this has been changed with webpack 2. See current README.

**Comment by volodymyr-tsaryk** [comment]
@CallMeXYZ did you resolve your issue ? I am having same

**Comment by CallMeXYZ** [comment]
@volodymyr-tsaryk  check above @jhnns answers. For simple varibles you may do sth like this  
```
{
    loader: "sass-loader",
    options: {
        data: "$var1: " + yourVar1+ ";"
    }
}
```

**Comment by volodymyr-tsaryk** [comment]
@CallMeXYZ that worked, thanks

**Comment by scott-thrillist** [comment]
So useful, glad Google led me here. Thanks all.

https://webpack.js.org/loaders/sass-loader/#environment-variables

**Comment by ShawnCorrigan** [comment]
@epegzz Your solution is great, although I'm wondering if there's a way to use it when requiring scss files. I think that it would make more sense to be able to `require('./style.css)({"background-color":"red"})` from your index.js file.

**Comment by epegzz** [comment]
@ShawnCorrigan although I can see use-cases for your proposal, it, unfortunately, does not play well with ES6 modules :(

**Comment by epegzz** [comment]
@ShawnCorrigan However, you could simply call `require(htmlWebpackPlguin.options.bgImage)` in your webpack config file:

```js
// webpack.config.js

const headerBackgroundImage = require(htmlWebpackPlguin.options.bgImage);

module.exports = {
  module: {
    rules: [{
      test: /\.scss$/,
      use: [
        // …
        { loader: "@epegzz/sass-vars-loader", options: {
          vars: {
            'header-background': headerBackgroundImage
          }
        }
      }]
    }]
  },
};
```

**Comment by ShawnCorrigan** [comment]
@epegzz Hmm okay. The idea was to not really modify the webpack.config.js file, although I suppose I could have another file that the webpack.config.js file uses to load the images. Thanks for the response!

**Comment by epegzz** [comment]
@ShawnCorrigan Sorry for the late reply, I somehow missed your response above.

But yeah, you're absolutely right. In most cases, you probably want to load all vars from a file and never touch the Webpack config again :)

**Comment by BruneXX** [comment]
Hi @volodymyr-tsaryk with one var works like a charm, but how to share multiple vars? is that possible? thanks!

**Comment by devtas** [comment]
> @kasu really liked your work so I went and forked it into a npm loader https://www.npmjs.com/package/jsontosass-loader

This guy no longer supports this lib. Sad.

**Comment by subvertallchris** [comment]
Anyone trying to use simple variables as described by above, the `data` key appears to have been changed to `prependData`. You'd now do this:

```
{
    loader: "sass-loader",
    options: {
        prependData: "$var1: " + yourVar1+ ";"
    }
}
```

**Comment by boltgolt** [comment]
If you're here through a google search, this has been renamed once more to `additionalData`, so:

```
{
	loader: "sass-loader",
	options: {
		additionalData: '$myColor: green;'
	}
}
```
