### ISSUE TITLE
Marked dependencies do not respect previous loaders in the pipe

### ISSUE THREAD

**Issue by tomhicks-bsf** [jtangelder/sass-loader#50]
Let's say main.scss has `@import 'some-settings.scss'` at the top. We have another loader that replaces 'some-settings.scss' with '/path/to/our/specific/settings-file.scss'. It compiles just fine, but the marked dependencies are incorrect. This is because sass-graph is used to mark dependencies *from the original source file, ignoring the actual piped content*, but node-sass is used to compile the sass from the piped content.

So the thing that marks the dependencies is marking them based off incorrect, "out-of-date" data. It should mark them based off the `content` parameter in the loader, not by reading in the file contents.

**Comment by jhnns** [comment]
You're right, but [this will probably be fixed](https://github.com/jtangelder/sass-loader/pull/29#issuecomment-63221951) as soon as node-sass 2.0 is ready-to-use.

**Comment by tomhicks-bsf** [comment]
OK I'll keep an eye on that. I've seen that sass-graph has been in, out, in, out, shake it all about, and that seems to pertain to this issue.

**Comment by izaakschroeder** [comment]
@tomhicks-bsf https://github.com/jtangelder/sass-loader/pull/53 probably maybe resolves this.

**Comment by jorrit** [comment]
Is this one fixed?
