### ISSUE TITLE
Release new version on NPM (with node-sass@2.0.1)

### ISSUE THREAD

**Issue by nkbt** [jtangelder/sass-loader#54]
At the moment published 0.4.0 uses old node-sass, which has build issues and `npm install fails` 

I can see that in master branch node-sass@2.0.1 is already used.

Thanks

**Comment by nkbt** [comment]
At the moment I am using     
```
"sass-loader": "git://github.com/jtangelder/sass-loader#master",
```
That works but is creepy

**Comment by nwhite89** [comment]
:+1: yeah I'm having to set ``node-sass: "~2.0.0"`` within my package.json which isn't the nicest especially being unknown whether it will deff work

**Comment by jhnns** [comment]
Running `npm install sass-loader` and inspecting the `package.json` outputs:

```javascript
  "dependencies": {
    "loader-utils": "^0.2.5",
    "node-sass": "^2.0.1",
    "sass-graph": "^1.0.3"
  },
```

**Comment by nwhite89** [comment]
I'm still getting it with ``1.2.2`` I've cleared cache for npm

**Comment by jhnns** [comment]
Try to run it in an empty folder. You've probably specified another version in your `package.json`.

**Comment by nwhite89** [comment]
ah yes your right that's very odd but thanks :+1:

**Comment by jhnns** [comment]
No problem
