### ISSUE TITLE
sass-graph expects .scss extention on all imports.

### ISSUE THREAD

**Issue by jsg2021** [jtangelder/sass-loader#56]
I've opened an issue with sass-graph: xzyfer/sass-graph#14

Just thought it should be echoed here.  If you @import something in your scss file that does not end in .scss the loader will bark.

**Comment by jhnns** [comment]
Thx

**Comment by saki7** [comment]
:+1: on this issue.

**Comment by jhnns** [comment]
Starting with 1.0.0, we don't depend on sass-graph anymore.
