### ISSUE TITLE
sourceMappingUrl is wrong

### ISSUE THREAD

**Issue by mekwall** [jtangelder/sass-loader#58]
I nearly got source maps to work, but it's outputting the wrong sourceMappingUrl. I am getting `../../..//build/sass.map` instead of `styles.css.map`. I am using sass-loader 0.4.1, webpack 1.4.15 and extract-text-webpack-plugin 0.3.8.

This is my configuration:

    var webPackConfig = {
        output: {
            path: path.join(__dirname, "build"),
            filename: "bundle.js"
        },
    
        entry: "./src/main.js",
        debug: true,
        devtool: "source-map",
    
        module: {
            loaders: [
                { test: /\.gif/, loader: "url?limit=10000&minetype=image/gif" },
                { test: /\.jpg/, loader: "url?limit=10000&minetype=image/jpg" },
                { test: /\.png/, loader: "url?limit=10000&minetype=image/png" },
                { test: /\.js$/, loader: "jsx" },
                { test: /\.json$/, loader: "json" },
                { test: /\.woff$/, loader: "url?limit=10000&minetype=application/font-woff" },
                { test: /\.ttf$/, loader: "file" },
                { test: /\.eot$/, loader: "file" },
                { test: /\.svg$/, loader: "file" },
                { test: /\.css/, loader: ExtractTextPlugin.extract("css?sourceMap") },
                { test: /\.scss$/, loader: ExtractTextPlugin.extract(
                    "css?sourceMap" +
                    "!sass?sourceMap&sourceMapContents=true" +
                    "&outputStyle=expanded" +
                    "&includePaths[]=" + require("node-bourbon").includePaths +
                    "&includePaths[]=" + (path.resolve(__dirname, "./node_modules"))
                )}
            ],
            noParse: /parse-latest.js/
        },
    
        plugins: [
            new webpack.optimize.OccurenceOrderPlugin(),
            new ExtractTextPlugin("styles.css")
        ],
    
        resolve: {
            modulesDirectories: ['node_modules'],
            extensions: ['', '.js', '.json']
        }
    }

Any ideas?

**Comment by jhnns** [comment]
I'll take a look

**Comment by mekwall** [comment]
@jhnns Any luck with this? I'd really love to get source maps to work, so if you have any pointers or want me to try something out I'm all ears :)

**Comment by jhnns** [comment]
Could you create a small test-case? I need to know more about your actual project structure, because source maps are working as expected in our repo.

**Comment by mekwall** [comment]
@jhnns I'll try to whip something together!

**Comment by mekwall** [comment]
Doh! The devserver we use overrid the `devtool` setting to `eval`. Changing it to `source-map` solved everything! Thanks anyway and sorry for taking up your time...

**Comment by jhnns** [comment]
No problem. :grinning:
