### ISSUE TITLE
import statements caveat

### ISSUE THREAD

**Issue by mgmorcos** [jtangelder/sass-loader#59]
sass/libsass#21 is resolved since 11/2014 but still cited as preventing `@import` statement resolution:

https://github.com/jtangelder/sass-loader/blob/9e7caca80f8a0908289cdbdfe8a80ae5e7e1781e/README.md#caveats

**Comment by jhnns** [comment]
#31

**Comment by mikeyamadeo** [comment]
Hi. I've just begun configuring with webpack and for the life of me hadn't be able to get imports to resolve w/ a combination of webpack aliasing and modulesDirectories using sass-loader.  

"File to import not found or unreadable" is my ever occurring error.

Alas, I read the sass-loader caveat. Just wanted to confirm my understanding after reading through the issues that a solution to this is still being worked on? @jhnns

Thanks!

**Comment by jhnns** [comment]
> Just wanted to confirm my understanding after reading through the issues that a solution to this is still being worked on?

Yes

**Comment by grrowl** [comment]
@mikeyamadeo until sass-loader gets whatever resolution features they need from libsass, you'll have to do like this:

`webpack.config.js`:
```js
      {
        test: /\.s?css$/,
        loaders: [
          'css',
          'sass?includePaths[]='+ path.resolve(__dirname, 'node_modules') +
            '&includePaths[]='+ path.resolve(__dirname, 'bower_components')
            // tells sass-loader to look in these dirs when resolving files
        ]
      }
```

`app.scss`:
```css
// These files are in the same directory as app.scss
@import "variables";
@import "breakpoints";

// These files are in the bower_components directory
@import "susy/sass/susy"; // resolves to bower_components/susy/sass/_susy.scss
@import "compass-breakpoint/stylesheets/breakpoint"; // resolves to compass-breakpoint/stylesheets/breakpoint.scss
```

If you use a lot of a library (such as pulling selective files from bootstrap), you could add that to your includePaths like `'&includePaths[]='+ path.resolve(__dirname, 'bower_components', 'bootstrap-sass', 'assets', 'stylesheets')`

**Comment by grrowl** [comment]
but note your webpack `alias:` settings will never be taken into consideration.

**Comment by mikeyamadeo** [comment]
@grrowl Thank You! I appreciate you taking the time to help me out on this. This does just the trick.
