### ISSUE TITLE
Add ?sync flag to trigger synchronous compilation

### ISSUE THREAD

**Issue by jhnns** [jtangelder/sass-loader#64]
Originated from pull-request #39

**Comment by kisenka** [comment]
Any ETA on this?

**Comment by jhnns** [comment]
Not yet. You could [switch `isSync` to `true`](https://github.com/jtangelder/sass-loader/blob/19d01ab0db9e8066d250134a6080b780b3064ad9/index.js#L27) in your local installation to test it. I heard that sync compilation is awful slow in sufficient complex projects so this has no priority for me.

**Comment by jhnns** [comment]
Stuck processes should be no issue with 2.0.0 anymore. So this flag is not necessary.
