### ISSUE TITLE
Abort trap: 6

### ISSUE THREAD

**Issue by haustraliaer** [jtangelder/sass-loader#65]
After upgrading to 1.0.0 I'm getting fairly inconsistent errors along the lines of:

```
Assertion failed: (handle->flags & UV_CLOSING), function uv__finish_close, file ../deps/uv/src/unix/core.c, line 171.
Abort trap: 6
```

Seems to be an issue with node-sass that has persisted into the pre-release sass-loader is using?

https://github.com/sass/node-sass/issues/713

**Comment by jenbennings** [comment]
I'm also getting this.

**Comment by jhnns** [comment]
Yep, I was also getting these. You need to stick with sass-loader `0.x` until this is fixed. :unamused:

**Comment by haustraliaer** [comment]
So close! The brief 30 seconds of custom importers was bliss.

**Comment by ryan1234** [comment]
+1 for this. =)

**Comment by morethanfire** [comment]
+1

**Comment by doylem** [comment]
Also seeing the same behaviour.

**Comment by andycmaj** [comment]
+1

had to back up to sass-loader@0.4.2 because 0.5.0 has a dependency on node-sass@3.0.0-pre which doesn't exist

**Comment by jcreamer898** [comment]
Thanks for the fix here @andycmaj, struggling with the same issue!

**Comment by jhnns** [comment]
I've managed to write a version of sass-loader that provides the same features while depending on node-sass `2.1.1`. It's on a [separate branch](https://github.com/jtangelder/sass-loader/tree/release/v0.6.0) and can be installed via `npm i sass-loader@0.6.x`. Please note, that sass-loader `0.6.0` is listing node-sass as `peerDependency` as well.

**Comment by nickdima** [comment]
@jhnns I'm still seeing this problem even with `sass-loader@0.6.` and `node-sass@2.1.1`
Is there some feature I shouldn't be using or something?

**Comment by alexhawkins** [comment]
Just wanted to iterate that this loader has been extremely troublesome for me. Slowing me down massively. Sometimes it works but mostly it crashes. At least i know what's causing it.

**Comment by akloeber** [comment]
For those still looking for a workaround: `sass-loader@0.6.0` does not work neither as it depends on  `node-sass@2.1.1` which, according to the comments in https://github.com/sass/node-sass/issues/713, is also one of the versions that provoke these errors.

The latest working version seems to be `node-sass@2.0.1` but even explicitely depending on `node-sass@2.0.1` as a peer dependency is not a workaround because it does not satisfy `^2.1.1`.

**Comment by jhnns** [comment]
Afaik `sass-loader@0.4.2` is the last version that does not bother you with errors

**Comment by akloeber** [comment]
Unfortunately `sass-loader@0.4.2` has dependency `"node-sass": "^2.0.1"` which means that the latest `node-sass@2.1.1` gets installed.

**Comment by alexhawkins** [comment]
For those of you trying to get this to work, you need to use `sass/node-sass#v3.0.0-alpha.1`, with `sass-loader@0.4.2` . You can see a working version of it here in a project I was recently working on [https://github.com/alexhawkins/UberDoku](https://github.com/alexhawkins/UberDoku )  Look at my `package.json` and `webpack.config`

**Comment by raphaelsaunier** [comment]
Same here; I had to downgrade to `0.4.2` (…and not `0.6.0`, as recommended in the README) to get rid of the errors.

sass/node-sass@fce099346a0c6e6fc6b9c8d4543fbbf077025118 allegedly fixes this issue, however even when using it, I kept getting random crashes with both `sass-loader@0.6.0` and `1.0.1`.

**Comment by jhnns** [comment]
@raphaelsaunier I've updated the README

**Comment by haustraliaer** [comment]
This seems totally stable for me now with the latest node-sass release - and pulling `"sass-loader": "1.0.0"` from npm gets the updated `node-sass@3.1.0`, despite sass-loader still specifying the beta.

I haven't tested with a large codebase full of imports yet, but I will likely get to it over the weekend.

**Comment by jhnns** [comment]
@haustraliaer that are good news. Please let me know if everything works as expected. I'll remove the note in the README then.

**Comment by alexduan** [comment]
This should probably be a separate issue, but after upgrading to 1.0.2 webpack will just completely hang.

**Comment by haustraliaer** [comment]
Yeah I'm on 1.0.0 so haven't seen that bug - you should log it separately.

**Comment by jhnns** [comment]
@alexduan this does not happen in our tests, so please try to narrow it down and open a separate issue.
