### ISSUE TITLE
problem with keyframes

### ISSUE THREAD

**Issue by jongbeau** [jtangelder/sass-loader#66]
I have the following code in my scss file:

@keyframes animatedBackground {
  from { background-position: 0 0; }
  to { background-position: 0 -166px; } 
}

When the sass loader runs, it fails with the message:
Module build failed: Error: Please check the validity of the CSS block starting from the line #7656

Also, the line numbers are not accurate which makes it very difficult to debug. Is there an way to run the loader from the command line so I can see the direct output?

**Comment by jorrit** [comment]
Is this bug still valid?
