### ISSUE TITLE
Just pulled v1.0.0 and get an error

### ISSUE THREAD

**Issue by justin808** [jtangelder/sass-loader#67]
I'm getting this error:

```
Assertion failed: (handle->flags & UV_CLOSING), function uv__finish_close, file ../deps/uv/src/unix/core.c, line 171.
```

I'm going to try reverting to the prior version to see if that fixes the issue.

After going to this version: "^0.4.0-beta.1", the error goes away.

I'm seeing other issues after updating all modules. I'll post an update shortly.

Just ran
```
npm i --save-dev node-sass
```
and went back to 1.0.0

and the prior error went away. Still some other issues, but might be unrelated.

**Comment by justin808** [comment]
No issues if you do the explicit install of the node-sass.

**Comment by marklundin** [comment]
What's the temp workaround for this? `npm install node-sass`?

**Comment by jhnns** [comment]
With `sass-loader 1.0.0` `node-sass` should now be a dependency of *your* project.

**Comment by nub4life** [comment]
I'm getting the same error, with node-sass 3.0.0-alpha.0 in my project's dependencies. Any suggestions?

**Comment by jhnns** [comment]
`node-sass@3.0.0-alpha.0` is – as the name suggests – not stable :wink:. Probably the same issues as #65
