### ISSUE TITLE
[Question] source-maps with css or sass?

### ISSUE THREAD

**Issue by ericfong** [jtangelder/sass-loader#7]
Hi, 

I am using sass-loader to compile sass code. Can we have the source-map to trace back the source file with webpack for sass?

Currently, I setup Sass-loader by

     { test: /\.scss/, loader: "style-loader!sass-loader?outputStyle=expanded" },

with 

        cache: true,
        debug: true,
        devtool: 'source-map',
        'output-pathinfo': true,

Is it possible to trace back the source sass file in chrome dev tools?

**Comment by cowwoc** [comment]
@nickdima @offminded Any updates?

**Comment by jhnns** [comment]
We should check if this is possible with the current beta version of node-sass.

The current master branch is [already using node-sass 2.0](https://github.com/jtangelder/sass-loader/blob/100f2a53c7fbbc8b19dde20f8a16c8c837049a8c/package.json#L23), so we can start playing with it now.

**Comment by kyle-johnson** [comment]
This works for me:

```
{ test: /\.scss$/, loader: ExtractTextPlugin.extract('style-loader',
 'css-loader?sourceMap!sass-loader?outputStyle=expanded&sourceMap=true&sourceMapContents=true') }
```

**Comment by schlaup** [comment]
It almost works...

With aboves config Chrome displays "stdin" as the source.

File name and path is missing. You need to change "sass-loader/index.js":

```
...

    opt.success = function (result) {
        markDependencies();
        var sourceMap = {};
        if (typeof result.map === 'string' && result.map !== '{}') {
            var sourceFilename = utils.getRemainingRequest(this);
            var current = utils.getCurrentRequest(this);
            var sourceMap = JSON.parse(result.map);
            sourceMap.sources = [sourceFilename];
            sourceMap.file = current;
        }
        callback(null, result.css, sourceMap);
    }.bind(this);

...
```

After this change you can map the source in Chrome's workspace and edit / save the file in Chrome as well.

Could you add this to the official NPM release?

Thanks!

**Comment by adri** [comment]
I can confirm the solution from @kyle-johnson. Thanks!

**Comment by jhnns** [comment]
Has been published as `v0.4.1`. I've added [instructions](https://github.com/jtangelder/sass-loader#source-maps) to the README.

**Comment by nickdima** [comment]
How are you guys live reloading the css when using `ExtractTextPlugin` for having source maps support? I'm asking this since HMR doesn't work with `ExtractTextPlugin`.

**Comment by adri** [comment]
I use two different configurations (dev and prod).

**Comment by nickdima** [comment]
But on dev you would want both source maps and hot/live reloading. How do you do that?

**Comment by Todilo** [comment]
@nickdima did you ever find a solution to this? I would really like hot/live reloading if posible, it's such a nice feature.

**Comment by jeffling** [comment]
@nickdima @Todilo what I've been doing is to just use webpack in watch mode instead of dev-server, and using http://livejs.com/ (or fb's flo or any other css reload plugin) to get live reloading.

**Comment by Todilo** [comment]
@jeffling ok, I was thinking of look into if there was a tool for that instead since I do not use the dev-server atm (getting everything working isomorphic in mvc5 is no simple task). Thank you I will try livejs.com. Guess I only need the css changes updates as reloading entire page when working with SPA seems like a bad idea.

**Comment by jeffling** [comment]
@Todilo if you use inline source maps, it should be updated I think.

**Comment by Todilo** [comment]
@jeffling  dont know how to set that up. However since I do most development in Chrome I setup a mapping from the the .scss from the server to the local location on the filesystem. Then I can both make changes in the browser(directly changin the scss files) as well as make changes in visual studio.

Still if I make changes in VS I dont get updated .scss file but well, whatever :) (if you dont have an easy guide on how to set tha tup).

**Comment by jhnns** [comment]
`inline-source-map` is the best option for development, because it requires no setup to retrieve the original source. However, it's not suitable for production, that's why we leave it up to the user to configure.

**Comment by tiemevanveen** [comment]
Thanks, this works indeed @kyle-johnson. But it doesn't if you would like to use React-Css-Modules. Any ideas? http://stackoverflow.com/questions/34434849/how-to-get-sourcemaps-working-for-react-css-modules

**Comment by JustMaier** [comment]
I started with what @kyle-johnson provided and then made it so it still had HMR in dev mode.

```js
var isDevelopment = process.env.ASPNETCORE_ENVIRONMENT === 'Development', //Replace with whatever you're using to determine if this is a dev env
    extractCSS = new ExtractTextPlugin('site.css', {disable: isDevelopment}),
    sassLoader = [
        'style',
        'css'+(isDevelopment? '?sourceMap=true': ''),
        'postcss',
        'sass'+(isDevelopment? '?outputStyle=expanded&sourceMap=true&sourceMapContents=true': '')
    ];

var config = {
    module: {
        loaders: [
            { test: /\.scss/, loader: extractCSS.extract(sassLoader) },
        ]
    },
    plugins: [
        extractCSS
    ]
};
```

**Comment by pdee999** [comment]
Here's what I did:

1) Make sure to include `devtool: "source-map",` before the module definition.
2)  Be sure to add the `?sourceMap` option to both the css-loader and sass-loader or pass a config property to the sass-loader.  

`loader: ExtractTextPlugin.extract('style-loader', 'css-loader?sourceMap!sass-loader?sourceMap'),`

or

`loader: ExtractTextPlugin.extract('style-loader', 'css-loader?sourceMap!sass-loader?config=sassLoader'),
sassLoader: {
        outFile:        './httpdocs/wp-content/themes/PDFK/build/styles.bundle.css',
        outputStyle:    'expanded',
        sourceMap:      'true'
    },`

Here's what my webpack.config.js looks like: 

`var path = require('path');
var ExtractTextPlugin = require("extract-text-webpack-plugin");
module.exports = {
    entry: './httpdocs/wp-content/themes/PDFK/js/scripts.core.js',
    output: {
        path: './httpdocs/wp-content/themes/PDFK/build/',
        filename: "scripts.bundle.js",
    },
    devtool: "source-map",
    module: {
        preLoaders: [
            {
                test: /.*\.js$/,
                exclude: [
                    /(node_modules|vendor|wp-admin|wp-includes|plugins|twentyfifteen|twentysixteen|twentyseventeen|libs)/
                ],
                loader: 'jshint-loader'
            }
        ],
        loaders: [
            {
                test: /.*\.js$/,
                exclude: [
                    /(node_modules|vendor|wp-admin|wp-includes|plugins|twentyfifteen|twentysixteen|twentyseventeen|libs)/
                ],
                loader: 'babel-loader',
                query: {
                    presets: ['es2015']
                }
            },
            {
                test: /.*\.js$/,
                exclude: [
                    /(node_modules|vendor|wp-admin|wp-includes|plugins|twentyfifteen|twentysixteen|twentyseventeen|libs)/
                ],
                loader: 'uglify'
            },
            {
                test: /\.(png|woff|woff2|eot|ttf|svg)(\?[0-9].+)?$/,
                //test: /.(png|woff(2)?|eot|ttf|svg)(?[a-z0-9=.]+)?$/,
                exclude: [
                    /(node_modules|vendor|wp-admin|wp-includes|plugins|twentyfifteen|twentysixteen|twentyseventeen|libs)/
                ],
                loader: 'url-loader?limit=100000'
            },
            // {
            //     test: /.*\.scss$/,
            //     exclude: [
            //         /(node_modules|vendor|wp-admin|wp-includes|plugins|twentyfifteen|twentysixteen|twentyseventeen|libs)/
            //     ],
            //     loader: 'style-loader!css-loader!sass-loader'
            // },
            {
                test: /.*\.scss$/,
                loader: ExtractTextPlugin.extract('style-loader', 'css-loader?sourceMap!sass-loader?config=sassLoader'),
                fallbackLoader: 'style-loader!css-loader!sass-loader'
            }
        ]
    },
    plugins: [
        new ExtractTextPlugin('styles.bundle.css')
    ],
    sassLoader: {
        outFile:        './httpdocs/wp-content/themes/PDFK/build/styles.bundle.css',
        outputStyle:    'expanded',
        sourceMap:      'true'
    },
    watch: false, // You need to keep the grunt process alive
    watchOptions: {
        aggregateTimeout: 500,
        // poll: true // Use this when you need to fallback to poll based watching (webpack 1.9.1+ only)
    },
    keepalive: false, // defaults to true for watch and dev-server otherwise false
};`

**Comment by gkhno** [comment]
{
        test: /\.(scss|sass)$/,
        loader: 'style!css?sourceMap!postcss!sass?sourceMap'
      },

this is directly from my config. (ejected create-react-app) it works just fine for me. You need to add `?sourceMap` to css loader.

**Comment by shannonsumner** [comment]
**I was able to get it working by doing the following:**

```
const path = require('path');
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
    entry: [
        path.join(__dirname, 'src/index')
    ],
    output: {
        path: path.join(__dirname, 'etc/designs/devstudio/clientlib'),
        publicPath: "/dist",
        filename: 'js/bundle.js'
    },
    devtool: 'source-map',
    module: {
        loaders: [
            {
                test: /\.js$/,
                exclude: /(node_modules|bower_components)/,
                loader: 'babel-loader',
                query: {
                    presets: [ 'es2015' ],
                    plugins: [ 'transform-runtime' ]
                }
            },
            {
                test: /(\.scss|\.css)$/,
                use: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: [
                        {
                            loader: 'css-loader',
                            options: {
                                sourceMap: true
                            }
                        },
                        {
                            loader: 'sass-loader',
                            options: {
                                sourceMap: true,
                                outFile: 'css/bundle.css',
                                outputStyle: 'expanded',
                            }
                        }
                    ],
                })
            },
            {
                test: /\.(png)$/,
                use: {
                    loader: 'url-loader',
                    options: {
                        limit: 100000,
                        outputPath: '../images/',
                        publicPath: '/dist/images/'
                    }
                },
            }, {
                test: /\.jpg$/,
                use: {
                    loader: 'file-loader',
                    options: {
                        outputPath: '../images/',
                        publicPath: '/dist/images/'
                    }
                }
            }, {
                test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
                use: {
                    loader: 'url-loader',
                    options: {
                        limit: 10000,
                        outputPath: '../fonts/',
                        publicPath: '/dist/fonts/',
                        mimetype: 'application/font-woff'
                    }
                }
            }, {
                test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
                use: {
                    loader: "file-loader",
                    options: {
                        outputPath: '../fonts/',
                        publicPath: '/dist/fonts/'
                    }
                }
            }
        ],
    },
    resolve: {
        modules: [ 'node_modules', './src' ]
    },
    plugins: [
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery'
        }),
        new ExtractTextPlugin({ filename: 'css/bundle.css', disable: false, allChunks: true }
        )
    ]
};
```

**Comment by xuyongli** [comment]
@shannonsumner And do you find that your css was not compiled when you  use disable option in new ExtractTextPlugin?

**Comment by shannonsumner** [comment]
@xuyongli I don't think I tried with disable: true
