### ISSUE TITLE
SCSS build error

### ISSUE THREAD

**Issue by stevebluck** [jtangelder/sass-loader#70]
Hi,

I'm getting an error with a specific SCSS file: https://github.com/danielguillan/bem-constructor

'Module build failed: 
        $e: #{&}#{$bem-element-separator}#{$element};
           ^
      Error reading values after 
      in /playground/app/styles/settings/_ben-constructor.scss (line 475, column 13)
 @ ./app/styles/main.scss 4:14-225'

Seems to work fine with other scss compilers.

What am I doing wrong?

**Comment by jostw** [comment]
Having the same problem too.

It works fine for me when the node-sass version was 3.0.0-pre,
but it failed recently as the node-sass version become 3.0.0-beta.4

@stevebluck simple workaround is replacing node-sass 3.0.0-beta.4 with version 3.0.0-alpha.0 manually, it works for me now.

Hope to fix this issue, thx.

**Comment by jhnns** [comment]
node-sass 3.0.0 is causing some trouble :cry:

#71

**Comment by jhnns** [comment]
I've managed to write a version of sass-loader that provides the same features while depending on node-sass `2.1.1`. It's on a [separate branch](https://github.com/jtangelder/sass-loader/tree/release/v0.6.0) and can be installed via `npm i sass-loader@0.6.x`. Please note, that sass-loader `0.6.0` is listing node-sass as `peerDependency` as well.

**Comment by stevebluck** [comment]
Sorry but I seem to be getting the exact same problem after installing sass-loader@0.6.x.

Am I supposed to do anything else to get this working?

**Comment by jhnns** [comment]
I suppose, this is a problem with node-sass/libsass itself, because sass-loader is just passing the input on.
