### ISSUE TITLE
You may not @extend an outer selector from within @media.

### ISSUE THREAD

**Issue by jongbeau** [jtangelder/sass-loader#72]
Hello,
I'm trying to build bootstrap-sass with sass-loader, and i'm getting the following error:
```
ERROR in ./~/css-loader!./~/sass-loader?outputStyle=expanded&includePaths[]=/Users/....../node_modules!./app/stylesheets/main.scss
Module build failed:
    .input-group-sm & {
                                     ^
      You may not @extend an outer selector from within @media.
You may only @extend selectors within the same directive.
From "@extend .input-sm" on line 48 of node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_input-groups.scss

      in /Users/jason/dev/goco-client/node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_forms.scss (line 189, column 39)
 @ ./app/stylesheets/main.scss 4:14-284
```

My relevant npm versions:
```
sass-loader@1.0.0
bootstrap-sass@3.3.4
node-sass@3.0.0-beta.4
```

Is this a known issue?

**Comment by joostfarla** [comment]
This is caused by a bug in libsass which has been solved in the latest 3.0 beta versions. Sass-loader v1.0.0 is bound to node-sass version 3.0.0-alpha, which provides the alpha libsass version containing this bug. See https://github.com/sass/libsass/issues/943 for details.

@jtangelder, could you upgrade the node-sass dependency to the latest 3.0 beta version?

**Comment by jongbeau** [comment]
It's actually using the 3.0.0-beta.4 version of node-sass.

**Comment by jongbeau** [comment]
It's actually using the 3.0.0-beta.4 version of node-sass.

**Comment by joostfarla** [comment]
I've tested with the latest libsass version, but the problem remains indeed. I guess we have to keep an eye on the related issue https://github.com/twbs/bootstrap-sass/issues/879.

For now I've created a workaround by adding a custom requirement to my ```package.json```, which points to an older (working) version of ```node-sass```:

```yaml
...
"node-sass": "sass/node-sass#v3.0.0-pre",
...
```

**Comment by AW-UC** [comment]
@joostfarla the issue would be: sass/libsass#943 (as also linked in https://github.com/twbs/bootstrap-sass/issues/879#issuecomment-88172909)

**Comment by jhnns** [comment]
Thx for the feedback, but this error does not seem to be related to sass-loader...

**Comment by AW-UC** [comment]
@jhnns that's correct. node-sass is already a peerDepency. Nothing more can be done.

**Comment by liuliangsir** [comment]
+1

**Comment by HamishClulee** [comment]
+1
