### ISSUE TITLE
Question about error output

### ISSUE THREAD

**Issue by kjs3** [jtangelder/sass-loader#75]
I'm not really getting any useful error output during webpack compilation.
For example, if I try to add two values with different units in sass, the build fails but there's no stdout output to the terminal telling me why. I just get something like…

```
Paused on exception: 'Cannot find module "!!/Users/kjs3/all_the_paths_I_put_in_includePaths[]"'
```

… in Chrome's console when I try to load the page.

Am I missing some config to get sass errors?

**Comment by jhnns** [comment]
[There are actually tests for error reporting](https://github.com/jtangelder/sass-loader/blob/05396a5d82f67dac5e4c8932da27212cb6df2aac/test/index.test.js#L39-L77), so I don't expect this issue to be a problem of sass-loader. Could you provide a minimal example of your project where the error occurs?

**Comment by kjs3** [comment]
This was my mistake. Errors were indeed getting through webpack but I wasn't passing them through my gulp watch task.
