### ISSUE TITLE
build modulesAssertion failed

### ISSUE THREAD

**Issue by glifchits** [jtangelder/sass-loader#80]
I get a command line error which causes the webpack compile to fail.

`> webpack --progress --watch --colors`

`66% 138/147 build modulesAssertion failed: (handle->flags & UV_CLOSING),  function uv__finish_close, file ../deps/uv/src/unix/core.c, line 209.
`

Can anyone give any insight? I've got `node-sass ^2.1.1` and `sass-loader ^0.6.0`

**Comment by glifchits** [comment]
I suppose its related to this? https://github.com/sass/node-sass/issues/713

**Comment by jhnns** [comment]
Yep. We need to track that issue, it's not a sass-loader thing.

**Comment by glifchits** [comment]
FWIW for anyone else who runs into this, I'm running `sass-loader: ^0.4.2` and its working great as far as I can tell.
