### ISSUE TITLE
sourceMappingUrl is wrong

### ISSUE THREAD

**Issue by frankrrr** [jtangelder/sass-loader#81]
Same problem here as #58, even when devtool = source-map.

```
/*# sourceMappingURL=../../../sass.map */
```

Just tried to run the demo test/sourceMap too, which isn't working either:

```
/*# sourceMappingURL=test/output/sass.map */
```

The file sass.map isn't generated. I'm using node-sass 3.0.0-beta.5 and sass-loader 1.0.1 and also tried other versions. Any ideas?

**Comment by jhnns** [comment]
Is the URL wrong or is the map file just not generated?

**Comment by frankrrr** [comment]
I think both, it should generate for example: styles.sourcemap.css.map (in stead of sass.map?)

**Comment by jhnns** [comment]
You're right. It looks like this has changed in webpack somehow... need to investigate.

**Comment by Jeloi** [comment]
+1

**Comment by jjeising** [comment]
With the current `webpack` 1.8.9 and `extract-text-plugin` the following will be outputted in the `.css` file:
```
…
/*# sourceMappingURL=js/sass.map */
/*# sourceMappingURL=app.css.map*/
```
The later `app.css.map` exists and contains the `.scss` content, while the first isn't generated (as before). Config is
```
        loader: ExtractTextPlugin.extract('css?sourceMap!sass?sourceMap')
```

When deleting the first line manually everything looks fine in the browser.

**Comment by jhnns** [comment]
Thx for investigating this.... so maybe we just need to remove all the `sourceMappingURL` references added by libsass?

**Comment by jjeising** [comment]
That could be a solution, though I haven't tested other configurations. Removing [this line](jtangelder/sass-loader/blob/master/index.js#L123) does not work, as the map from `libsass` is needed. Maybe there should be an option for `libsass` to generate a source map without adding a reference?

**Comment by jhnns** [comment]
> Maybe there should be an option for libsass to generate a source map without adding a reference

Well, that option doesn't make sense from libsass' point of view ^^

**Comment by paddyforan** [comment]
Forgive me if I'm an idiot, but [isn't there already an option for that?](https://github.com/sass/node-sass/blob/b50533ae6862097d17711f15f99cad711808790c/README.md#omitsourcemapurl)

**Comment by jjeising** [comment]
Adding
```javascript
  if (opt.sourceMap) {
    …
    opt.sourceMap = this.options.output.path + '/sass.map';
+   opt.omitSourceMapUrl = true;
  }
```
works fine for me.

**Comment by jhnns** [comment]
I'll try that out, thanks!

**Comment by newtriks** [comment]
Following the recommended setup I get:

```
/*# sourceMappingURL=dist/sass.map */
/*# sourceMappingURL=styles.css.map*/
```

However, sourcemaps seem to work fine on first glance. I do encounter the same issue made by the original poster if I use `webpack-dev-server` and get the following url in my css:

`/*# sourceMappingURL=../../../../../../sass.map */`

In this case source maps do not work at all. Does anyone have a working solution for sourcemaps and webpack dev server? Workaround https://github.com/jtangelder/sass-loader/issues/92 does not seem to work either...

```
{
            test: /\.scss$/,
            loader: ExtractTextPlugin.extract(
                'style',
                'css?sourceMap!sass?outputStyle=expanded&sourceMap=true&sourceMapContents=true&' +
                'includePaths[]=' + bower_dir + '&' +
                'includePaths[]=' + node_dir)
        }
```

**Comment by newtriks** [comment]
I built a separate prototype app and all seems to work fine, gonna debug this app and determine why this occurs, if only for my sanity...

**Comment by jjeising** [comment]
Will this be added to the official distribution at some point?

**Comment by jhnns** [comment]
Yep. See #123

**Comment by jjeising** [comment]
Thanks!
