### ISSUE TITLE
npm versions not matching with github releases

### ISSUE THREAD

**Issue by matmuchrapna** [jtangelder/sass-loader#83]
Thanks for plugin. just wondering.

**Comment by jdlehman** [comment]
This is because there is work being done on another [branch](https://github.com/jtangelder/sass-loader/tree/release/v0.6.0) using node-sass `2.1.1` since `^3.0.0` is not stable.

See the discussion [here](https://github.com/jtangelder/sass-loader/issues/71#issuecomment-89267609)

**Comment by matmuchrapna** [comment]
Thanks
