### ISSUE TITLE
Publish new versions to npm.

### ISSUE THREAD

**Issue by daniel-norman-sociomantic** [jtangelder/sass-loader#85]
https://www.npmjs.com/package/sass-loader 

Seems like 1.0.0 hasn't been published.

**Comment by daniel-norman-sociomantic** [comment]
My bad.
▶ npm view sass-loader

{ name: 'sass-loader',
  description: 'Sass loader for webpack',
  'dist-tags': { latest: '0.6.0' },
  versions:
   [ '0.0.1',
     '0.0.2',
     '0.1.0',
     '0.1.1',
     '0.2.0',
     '0.3.0',
     '0.3.1',
     '0.4.0-beta.1',
     '0.4.0',
     '0.4.1',
     '0.4.2',
     '0.5.0',
     '0.6.0',
     '1.0.0',
     '1.0.1' ],

**Comment by daniel-norman-sociomantic** [comment]
My bad.
▶ npm view sass-loader

{ name: 'sass-loader',
  description: 'Sass loader for webpack',
  'dist-tags': { latest: '0.6.0' },
  versions:
   [ '0.0.1',
     '0.0.2',
     '0.1.0',
     '0.1.1',
     '0.2.0',
     '0.3.0',
     '0.3.1',
     '0.4.0-beta.1',
     '0.4.0',
     '0.4.1',
     '0.4.2',
     '0.5.0',
     '0.6.0',
     '1.0.0',
     '1.0.1' ],

**Comment by jhnns** [comment]
No problem. `0.6.0` *is* actually the latest version that has been published. But that was a compatibility fix for an older version.
