### ISSUE TITLE
Include Paths with space and special characters

### ISSUE THREAD

**Issue by alansouzati** [jtangelder/sass-loader#89]
Hi,

  Great job on the sass-loader. I'm trying to use includePaths=[] property with a path that has a folder with spaces and special character.

  I was expecting that to work, but I get the following error:

```bash
ERROR in ./~/css-loader!./~/sass-loader?outputStyle=expanded&includePaths[]="/path/Testing & Space/app-name/node_modules"!./src/scss/index.scss
Module build failed: file to import not found or unreadable: index
Current dir:  (4:9)
 @ ./src/scss/index.scss 4:14-238 12:19-243
```

If I rename the folder to not have spaces or special character, everything works fine. But it would be nice if this tool supports that.

Alan

**Comment by jhnns** [comment]
How do you configure the sass-loader in your `webpack.config`?

**Comment by alansouzati** [comment]
This is how I'm using the sass-loader inside webpack:

```javascript
var path = require('path');
...
{
  test: /\.scss$/,
  loader: 'style!css!sass?outputStyle=expanded&'+
        "includePaths[]=" +
        (path.resolve(process.cwd(), "node_modules"))
}
```

**Comment by jhnns** [comment]
@sokra How do the paths need to be escaped?

**Comment by jorrit** [comment]
The params are formatted like URI's. Have you tried URI encoding? It is just a guess.

**Comment by sokra** [comment]
yep, url encoding `%20`

**Comment by jhnns** [comment]
Is this still an issue?

**Comment by alansouzati** [comment]
I will try it again later today and get back to you guys.

**Comment by alansouzati** [comment]
Hi guys, doing URI encoding solves the problem. Thanks @jorrit for the tip!

Do you think the encoding part could be inside `sass-loader`? If yes, I can send a PR!

Here is my updated webpack config:

```
var path = require('path');
...
{
  test: /\.scss$/,
  loader: 'style!css!sass?outputStyle=expanded&'+
        "includePaths[]=" +
        (encodeURIComponent(path.resolve(process.cwd(), "node_modules")))
}
```

**Comment by jorrit** [comment]
I think webpack handles translating the input parameters so each plugin doesn't have to do that. It is the responsibility of the configuration writer to use the right syntax. Or maybe I am misunderstanding the thing you want to submit a PR about.

**Comment by jhnns** [comment]
Yes, honestly, using `encodeURIComponent` is counter-intuitive. On the other hand, the configuration writer is the only person who can escape it properly because they know where the characters belong to. Is `&` part of the config or is it used to distinguish different parameters?

**Comment by jorrit** [comment]
You can maybe try:
```
{
  test: /\.scss$/,
  loader: 'style!css!sass',
  query: {
    outputStyle: 'expanded',
    includePaths: [
        path.resolve(process.cwd(), "node_modules")
    ]
  }
}
```
