### ISSUE TITLE
Make latest version available via npm

### ISSUE THREAD

**Issue by bgannonPL** [jtangelder/sass-loader#93]
Hi, it looks like the latest version of sass-loader on npm is 0.6.0. I'm running into a libsass parse error that appears to be fixed in later versions (and supported by recent versions of node-sass and sass-loader). Would like to be able to get the latest via npm. Thanks-

**Comment by codedsignal** [comment]
@bgannonPL I have the same issue. Am currently using @oliverturner/sass-loader as a quick fix while I get a PR together

**Comment by jhnns** [comment]
Remove the `sass-loader` entry in your `package.json` and run `npm i sass-loader@1.x --save`. This should (currently) pull `node-sass@3.1.1`

**Comment by codedsignal** [comment]
@jhnns Much appreciated

**Comment by bgannonPL** [comment]
@jhnns Great, thanks
