### ISSUE TITLE
Vairable value can not be #DDDDD

### ISSUE THREAD

**Issue by xieaolin** [jtangelder/sass-loader#96]
Hi ~~ Thanks your loader first !

```scss
$test: #DDDDD;
```

I get error on build scss file with the code above , I try to fix it and found no matter what the name is it will be ok , but the value must not be `#DDDDDD`.

```shell
ERROR in ./~/css-loader!./~/sass-loader!./_assets/css/main.scss
Module build failed:
$test: #DDDDD;
     ^
      Error reading values after :
      in /Users/xieaolin/vagrant_xl/www/my_blog/_assets/css/main.scss (line 5, column 7)
 @ ./_assets/css/main.scss 4:14-121
```

**Comment by jhnns** [comment]
Is 5 times D or 6 times D? ^^ `#DDDDD` is no valid CSS color, `#DDDDDD` is.

**Comment by xieaolin** [comment]
Oh ! My apologize ...
